# Mid-frequency words G-P
MID_WORDS_B = [
    ("gadget", "/ˈɡædʒɪt/", "n.", "小工具；小装置；小玩意儿", "He loves buying electronic gadgets.", "他喜欢买电子小工具。"),
    ("galaxy", "/ˈɡæləksi/", "n.", "银河；星系；一群杰出的人", "The Milky Way is our home galaxy.", "银河系是我们的家园星系。"),
    ("gallery", "/ˈɡæləri/", "n.", "画廊；美术馆；长廊", "The art gallery opens at 10 am.", "美术馆上午10点开门。"),
    ("gamble", "/ˈɡæmbl/", "v./n.", "赌博；冒险；打赌", "He lost all his money gambling.", "他赌博输掉了所有的钱。"),
    ("gap", "/ɡæp/", "n.", "缺口；差距；间隙", "There is a wide gap between rich and poor.", "贫富之间存在巨大差距。"),
    ("garment", "/ˈɡɑːmənt/", "n.", "衣服；服装；外衣", "The garment industry employs many workers.", "服装业雇用了许多工人。"),
    ("gasp", "/ɡɑːsp/", "v./n.", "喘息；倒抽气；渴望", "She gasped in surprise.", "她惊讶地倒抽一口气。"),
    ("gauge", "/ɡeɪdʒ/", "n./v.", "计量器；规格；测量", "The fuel gauge shows half empty.", "油量表显示一半空。"),
    ("gaze", "/ɡeɪz/", "v./n.", "凝视；注视；盯着看", "She gazed out the window.", "她凝视着窗外。"),
    ("gear", "/ɡɪər/", "n./v.", "齿轮；装备；调整", "The car has automatic gear transmission.", "这辆车有自动变速器。"),
    ("gene", "/dʒiːn/", "n.", "基因；遗传因子", "The gene determines eye color.", "基因决定眼睛颜色。"),
    ("generalize", "/ˈdʒenrəlaɪz/", "v.", "概括；推广；使一般化", "It is unfair to generalize from one example.", "根据一个例子进行概括是不公平的。"),
    ("generate", "/ˈdʒenəreɪt/", "v.", "产生；生成；发电", "The wind turbines generate electricity.", "风力涡轮机发电。"),
    ("generous", "/ˈdʒenərəs/", "adj.", "慷慨的；大方的；宽厚的", "She donated a generous amount to charity.", "她向慈善机构捐赠了一大笔钱。"),
    ("genetic", "/dʒəˈnetɪk/", "adj.", "遗传的；基因的", "Genetic engineering has advanced rapidly.", "基因工程发展迅速。"),
    ("genius", "/ˈdʒiːniəs/", "n.", "天才；天赋；才华", "Mozart was a musical genius.", "莫扎特是音乐天才。"),
    ("genuine", "/ˈdʒenjuɪn/", "adj.", "真正的；真诚的；真实的", "Her apology seemed genuine.", "她的道歉看起来很真诚。"),
    ("geography", "/dʒiˈɒɡrəfi/", "n.", "地理；地形；地理学", "She studied geography at university.", "她在大学学习地理。"),
    ("geology", "/dʒiˈɒlədʒi/", "n.", "地质学；地质", "Geology helps us understand the Earths history.", "地质学帮助我们了解地球历史。"),
    ("geometry", "/dʒiˈɒmətri/", "n.", "几何；几何学", "Geometry deals with shapes and sizes.", "几何学研究形状和大小。"),
    ("germ", "/dʒɜːm/", "n.", "细菌；病菌；萌芽", "Wash your hands to kill germs.", "洗手以杀死细菌。"),
    ("gesture", "/ˈdʒestʃər/", "n./v.", "手势；姿势；表示", "He made a peace gesture.", "他做了一个和平手势。"),
    ("giant", "/ˈdʒaɪənt/", "adj./n.", "巨大的；巨人；巨头", "The company is a giant in the tech industry.", "该公司是科技行业的巨头。"),
    ("glimpse", "/ɡlɪmps/", "n./v.", "一瞥；瞥见；粗略一看", "She caught a glimpse of him in the crowd.", "她在人群中瞥见了他。"),
    ("globe", "/ɡləʊb/", "n.", "地球；球体；地球仪", "The globe shows all the continents.", "地球仪显示了所有大陆。"),
    ("gloomy", "/ˈɡluːmi/", "adj.", "阴暗的；忧郁的；令人沮丧的", "The weather was gloomy all day.", "一整天天气阴沉。"),
    ("glory", "/ˈɡlɔːri/", "n.", "光荣；荣誉；辉煌", "The team returned home with glory.", "该队带着荣誉回家了。"),
    ("glow", "/ɡləʊ/", "v./n.", "发光；发热；红光", "The stars glowed in the night sky.", "星星在夜空中发光。"),
    ("glue", "/ɡluː/", "n./v.", "胶水；粘合；粘贴", "Use glue to stick the pieces together.", "用胶水把碎片粘在一起。"),
    ("gorgeous", "/ˈɡɔːdʒəs/", "adj.", "华丽的；极好的；美丽的", "The sunset was absolutely gorgeous.", "日落美极了。"),
    ("gossip", "/ˈɡɒsɪp/", "n./v.", "八卦；闲话；流言蜚语", "Dont listen to office gossip.", "不要听办公室的闲话。"),
    ("grab", "/ɡræb/", "v./n.", "抓住；抢夺；夺取", "He grabbed the opportunity immediately.", "他立即抓住了这个机会。"),
    ("grace", "/ɡreɪs/", "n./v.", "优雅；恩惠；宽限", "She moved with natural grace.", "她动作自然优雅。"),
    ("grade", "/ɡreɪd/", "n./v.", "等级；成绩；评分", "She received good grades this semester.", "她这学期成绩很好。"),
    ("gradual", "/ˈɡrædʒuəl/", "adj.", "逐渐的；渐进的", "There has been a gradual improvement.", "有了逐渐的改善。"),
    ("graduate", "/ˈɡrædʒueɪt/", "v./n.", "毕业；毕业生；研究生", "She graduated from Peking University.", "她毕业于北京大学。"),
    ("grain", "/ɡreɪn/", "n.", "谷物；颗粒；纹理", "The country exports grain to other nations.", "该国向其他国家出口谷物。"),
    ("grand", "/ɡrænd/", "adj.", "宏伟的；重大的；总的", "The grand palace attracts many tourists.", "宏伟的宫殿吸引了许多游客。"),
    ("grant", "/ɡrɑːnt/", "v./n.", "授予；准予；补助金", "The government granted permits for the project.", "政府批准了该项目的许可证。"),
    ("graph", "/ɡræf/", "n./v.", "图表；图形；用图表表示", "The graph shows the growth trend.", "图表显示了增长趋势。"),
    ("grasp", "/ɡrɑːsp/", "v./n.", "抓住；理解；掌握", "She grasped the concept immediately.", "她立刻理解了这个概念。"),
    ("grateful", "/ˈɡreɪtfl/", "adj.", "感激的；感谢的；令人愉快的", "Im grateful for your help.", "我感谢你的帮助。"),
    ("gratitude", "/ˈɡrætɪtjuːd/", "n.", "感激；感恩；感谢", "I express my sincere gratitude.", "我表达我诚挚的感谢。"),
    ("grave", "/ɡreɪv/", "n./adj.", "坟墓；严重的；严肃的", "The situation is very grave.", "形势非常严峻。"),
    ("gravity", "/ˈɡrævəti/", "n.", "重力；严肃；严重性", "He realized the gravity of the situation.", "他意识到情况的严重性。"),
    ("graze", "/ɡreɪz/", "v.", "放牧；吃草；擦过", "Cattle grazed in the meadow.", "牛在草地上吃草。"),
    ("grease", "/ɡriːs/", "n./v.", "油脂；润滑油；涂油", "The mechanic cleaned the grease off his hands.", "机械师擦掉手上的油脂。"),
    ("greed", "/ɡriːd/", "n.", "贪婪；贪心；贪食", "His greed led to his downfall.", "他的贪婪导致了他的垮台。"),
    ("greenhouse", "/ˈɡriːnhaʊs/", "n.", "温室；暖房", "Greenhouse gases cause global warming.", "温室气体导致全球变暖。"),
    ("grief", "/ɡriːf/", "n.", "悲伤；悲痛；伤心", "She was overcome with grief.", "她悲痛欲绝。"),
    ("grieve", "/ɡriːv/", "v.", "悲伤；哀悼；使伤心", "The family grieved for their loss.", "家人为失去亲人而悲伤。"),
    ("grind", "/ɡraɪnd/", "v./n.", "磨碎；碾碎；苦差事", "Grind the coffee beans before brewing.", "冲泡前磨碎咖啡豆。"),
    ("grip", "/ɡrɪp/", "v./n.", "紧握；抓牢；掌握", "The tire provides good grip on wet roads.", "轮胎在湿路上抓地力好。"),
    ("grocery", "/ˈɡrəʊsəri/", "n.", "杂货店；食品杂货", "I need to buy some groceries.", "我需要买些食品杂货。"),
    ("gross", "/ɡrəʊs/", "adj./n./v.", "总的；毛的；令人恶心的", "The gross profit margin is 30%.", "毛利润率为30%。"),
    ("guarantee", "/ˌɡærənˈtiː/", "v./n.", "保证；担保；保修", "The product is guaranteed for two years.", "本产品保修两年。"),
    ("guard", "/ɡɑːd/", "n./v.", "守卫；保护；警惕", "Security guards patrol the building.", "保安在大楼巡逻。"),
    ("guess", "/ɡes/", "v./n.", "猜测；推测；猜想", "Can you guess my age?", "你能猜出我的年龄吗？"),
    ("guidance", "/ˈɡaɪdns/", "n.", "指导；引导；导航", "Students need guidance from teachers.", "学生需要老师的指导。"),
    ("guideline", "/ˈɡaɪdlaɪn/", "n.", "指南；方针；指导原则", "Follow the safety guidelines.", "遵守安全指南。"),
    ("guilty", "/ˈɡɪlti/", "adj.", "有罪的；内疚的；有过失的", "The jury found him guilty of murder.", "陪审团判定他犯有谋杀罪。"),
    ("gulf", "/ɡʌlf/", "n.", "海湾；鸿沟；分歧", "There is a gulf between theory and practice.", "理论和实践之间存在鸿沟。"),
    ("gum", "/ɡʌm/", "n.", "牙龈；口香糖；树胶", "Chewing gum is not allowed in class.", "课堂上不允许嚼口香糖。"),
    ("gymnasium", "/dʒɪmˈneɪziəm/", "n.", "体育馆；健身房", "The school has a large gymnasium.", "学校有一个大型体育馆。"),
    ("habitat", "/ˈhæbɪtæt/", "n.", "栖息地；生长地", "The forest is the natural habitat of many species.", "森林是许多物种的自然栖息地。"),
    ("hail", "/heɪl/", "n./v.", "冰雹；欢呼；招呼", "The discovery was hailed as a breakthrough.", "这一发现被誉为突破。"),
    ("halt", "/hɔːlt/", "v./n.", "停止；暂停；中断", "The project came to a halt due to funding issues.", "该项目因资金问题停止。"),
    ("hamper", "/ˈhæmpər/", "v./n.", "妨碍；阻碍；阻碍物", "Bad weather hampered rescue efforts.", "恶劣天气阻碍了救援工作。"),
    ("handbook", "/ˈhændbʊk/", "n.", "手册；指南；便览", "Read the handbook before using the equipment.", "使用设备前请阅读手册。"),
    ("handful", "/ˈhændfʊl/", "n.", "一把；少数；少量", "Only a handful of people attended.", "只有少数人参加。"),
    ("handle", "/ˈhændl/", "v./n.", "处理；操作；把手", "He knows how to handle the situation.", "他知道如何处理这种情况。"),
    ("handy", "/ˈhændi/", "adj.", "便利的；手边的；手巧的", "This tool is very handy.", "这个工具非常方便。"),
    ("harassment", "/ˈhærəsmənt/", "n.", "骚扰；困扰；烦恼", "Workplace harassment is illegal.", "职场骚扰是违法的。"),
    ("harbor", "/ˈhɑːbər/", "n./v.", "港口；海港；心怀", "The ship entered the harbor.", "船进了港口。"),
    ("hardware", "/ˈhɑːdweər/", "n.", "硬件；五金制品", "The store sells computer hardware.", "这家店卖电脑硬件。"),
    ("harm", "/hɑːm/", "n./v.", "伤害；损害；危害", "Smoking does harm to your health.", "吸烟有害健康。"),
    ("harmony", "/ˈhɑːməni/", "n.", "和谐；协调；融洽", "The two groups live in harmony.", "这两组人和睦相处。"),
    ("harvest", "/ˈhɑːvɪst/", "n./v.", "收获；收割；收成", "The farmers harvested their crops.", "农民们收割了庄稼。"),
    ("harsh", "/hɑːʃ/", "adj.", "严厉的；严酷的；刺耳的", "The punishment was too harsh.", "惩罚太严厉了。"),
    ("haste", "/heɪst/", "n.", "匆忙；急忙；草率", "More haste, less speed.", "欲速则不达。"),
    ("hatred", "/ˈheɪtrɪd/", "n.", "仇恨；憎恨；厌恶", "He looked at them with hatred.", "他仇恨地看着他们。"),
    ("haul", "/hɔːl/", "v./n.", "拖运；牵引；运送", "The truck hauls goods across the country.", "卡车在全国各地运送货物。"),
    ("haunt", "/hɔːnt/", "v./n.", "萦绕；困扰；常去", "The memory haunted him for years.", "记忆困扰了他多年。"),
    ("haven", "/ˈheɪvn/", "n.", "避风港；安全场所；避难所", "The park is a haven for wildlife.", "这个公园是野生动物的避风港。"),
    ("hazard", "/ˈhæzəd/", "n./v.", "危险；危害；冒险", "Smoking is a health hazard.", "吸烟危害健康。"),
    ("heading", "/ˈhedɪŋ/", "n.", "标题；方向；航向", "The heading of the article is misleading.", "文章的标题具有误导性。"),
    ("headline", "/ˈhedlaɪn/", "n.", "标题；头条新闻", "The news headlines are alarming.", "新闻标题令人担忧。"),
    ("headquarters", "/ˌhedˈkwɔːtəz/", "n.", "总部；司令部；指挥部", "The companys headquarters is in New York.", "公司总部在纽约。"),
    ("heal", "/hiːl/", "v.", "治愈；愈合；康复", "Time heals most wounds.", "时间能治愈大多数创伤。"),
    ("heap", "/hiːp/", "n./v.", "堆；大量；堆积", "There is a heap of work to do.", "有一大堆工作要做。"),
    ("hearing", "/ˈhɪərɪŋ/", "n.", "听力；听觉；审讯", "The court will hold a hearing next week.", "法院下周举行听证会。"),
    ("heave", "/hiːv/", "v./n.", "举起；起伏；喘息", "She heaved a sigh of relief.", "她松了一口气。"),
    ("heaven", "/ˈhevn/", "n.", "天堂；天空；极乐", "The smell from the kitchen was heavenly.", "厨房的气味美妙极了。"),
    ("hedge", "/hedʒ/", "n./v.", "树篱；对冲；回避", "The garden is surrounded by a hedge.", "花园被树篱环绕。"),
    ("heighten", "/ˈhaɪtn/", "v.", "提高；增加；加强", "The music heightened the tension.", "音乐加剧了紧张气氛。"),
    ("heir", "/eər/", "n.", "继承人；后嗣", "He is the heir to the throne.", "他是王位继承人。"),
    ("helicopter", "/ˈhelɪkɒptər/", "n.", "直升机", "The helicopter landed on the roof.", "直升机降落在屋顶上。"),
    ("hell", "/hel/", "n.", "地狱；苦境；极糟的经历", "The traffic was absolute hell.", "交通状况糟透了。"),
    ("helmet", "/ˈhelmɪt/", "n.", "头盔；安全帽；钢盔", "You must wear a helmet when cycling.", "骑车时必须戴头盔。"),
    ("herb", "/hɜːb/", "n.", "草本植物；香草；草药", "She grows herbs in her garden.", "她在花园里种香草。"),
    ("herd", "/hɜːd/", "n./v.", "兽群；牧群；放牧", "A herd of cattle grazed in the field.", "一群牛在田野里吃草。"),
    ("heritage", "/ˈherɪtɪdʒ/", "n.", "遗产；传统；继承物", "The Great Wall is a world heritage site.", "长城是世界遗产。"),
    ("hesitate", "/ˈhezɪteɪt/", "v.", "犹豫；踌躇；迟疑", "If you need anything, dont hesitate to ask.", "如果你需要什么，尽管问。"),
    ("highlight", "/ˈhaɪlaɪt/", "v./n.", "强调；突出；亮点", "The highlight of the trip was visiting the museum.", "这次旅行的亮点是参观博物馆。"),
    ("highway", "/ˈhaɪweɪ/", "n.", "公路；高速公路；主干道", "The highway connects the two cities.", "这条高速公路连接两座城市。"),
    ("hijack", "/ˈhaɪdʒæk/", "v./n.", "劫持；抢劫；绑架", "The plane was hijacked by terrorists.", "飞机被恐怖分子劫持。"),
    ("hike", "/haɪk/", "n./v.", "远足；徒步旅行；涨价", "We went hiking in the mountains.", "我们去山里远足了。"),
    ("hinder", "/ˈhɪndər/", "v.", "阻碍；妨碍；阻止", "Lack of funding hindered the project.", "缺乏资金阻碍了该项目。"),
    ("hinge", "/hɪndʒ/", "n./v.", "铰链；合页；关键", "The door hinge needs oiling.", "门铰链需要上油。"),
    ("hint", "/hɪnt/", "n./v.", "暗示；提示；线索", "She gave him a hint about the answer.", "她给了他一个关于答案的提示。"),
    ("hip", "/hɪp/", "n./adj.", "臀部；时髦的；新潮的", "She broke her hip in a fall.", "她摔倒时臀部骨折。"),
    ("historian", "/hɪˈstɔːriən/", "n.", "历史学家；史学工作者", "The historian wrote a book about the war.", "历史学家写了一本关于战争的书。"),
    ("hitherto", "/ˌhɪðəˈtuː/", "adv.", "迄今；到目前为止", "This is a hitherto unknown species.", "这是一种迄今未知的物种。"),
    ("hobby", "/ˈhɒbi/", "n.", "业余爱好；嗜好", "Reading is my favorite hobby.", "阅读是我最喜欢的爱好。"),
    ("hoist", "/hɔɪst/", "v./n.", "升起；吊起；提升", "The sailors hoisted the flag.", "水手们升起了旗帜。"),
    ("holder", "/ˈhəʊldər/", "n.", "持有人；持有者；容器", "The record holder still holds the world record.", "这项纪录保持者仍保持着世界纪录。"),
    ("hollow", "/ˈhɒləʊ/", "adj./v./n.", "中空的；空洞的；凹陷", "The tree trunk was hollow.", "树干是中空的。"),
    ("holy", "/ˈhəʊli/", "adj.", "神圣的；圣洁的；虔诚的", "Jerusalem is a holy city.", "耶路撒冷是一座圣城。"),
    ("homogeneous", "/ˌhɒməˈdʒiːniəs/", "adj.", "同质的；同类的；均匀的", "The population is relatively homogeneous.", "人口相对同质。"),
    ("hook", "/hʊk/", "n./v.", "钩子；挂钩；钩住", "He hung his coat on the hook.", "他把外套挂在钩子上。"),
    ("hop", "/hɒp/", "v./n.", "单脚跳；跳跃；蹦跳", "The rabbit hopped across the field.", "兔子跳过田野。"),
    ("horizon", "/həˈraɪzn/", "n.", "地平线；眼界；视野", "Travel broadens your horizons.", "旅行开阔你的眼界。"),
    ("hormone", "/ˈhɔːməʊn/", "n.", "激素；荷尔蒙", "Hormones regulate many bodily functions.", "激素调节许多身体功能。"),
    ("horn", "/hɔːn/", "n.", "角；喇叭；号角", "The car horn was loud.", "汽车喇叭很响。"),
    ("horrible", "/ˈhɒrəbl/", "adj.", "可怕的；极坏的；令人恐惧的", "There was a horrible accident on the highway.", "高速公路上发生了一起可怕的事故。"),
    ("horror", "/ˈhɒrər/", "n.", "恐怖；震惊；厌恶", "She watched the horror movie with her hands over her eyes.", "她双手捂着眼睛看恐怖片。"),
    ("hostage", "/ˈhɒstɪdʒ/", "n.", "人质；抵押品", "The hostages were released unharmed.", "人质安全获释。"),
    ("hostile", "/ˈhɒstaɪl/", "adj.", "敌对的；不友好的；不利的", "The audience gave a hostile response.", "观众反应敌意。"),
    ("household", "/ˈhaʊshəʊld/", "n./adj.", "家庭；住户；家用的", "The product is a household name.", "该产品家喻户晓。"),
    ("housing", "/ˈhaʊzɪŋ/", "n.", "住房；房屋；外壳", "The city needs more affordable housing.", "该市需要更多经济适用房。"),
    ("hover", "/ˈhɒvər/", "v.", "盘旋；徘徊；悬停", "The helicopter hovered over the building.", "直升机在大楼上空盘旋。"),
    ("hug", "/hʌɡ/", "v./n.", "拥抱；紧抱；抱住", "She hugged her children tightly.", "她紧紧拥抱孩子们。"),
    ("humanity", "/hjuːˈmænəti/", "n.", "人类；人性；人道", "The disaster was a tragedy for humanity.", "这场灾难是人类的悲剧。"),
    ("humble", "/ˈhʌmbl/", "adj./v.", "谦虚的；谦卑的；使谦卑", "He remains humble despite his success.", "尽管成功了，他依然谦虚。"),
    ("humidity", "/hjuːˈmɪdəti/", "n.", "湿度；潮湿；湿气", "The humidity in summer can be unbearable.", "夏天的湿度让人难以忍受。"),
    ("humor", "/ˈhjuːmər/", "n./v.", "幽默；诙谐；迁就", "She has a great sense of humor.", "她很有幽默感。"),
    ("hunt", "/hʌnt/", "v./n.", "打猎；搜索；追捕", "The police are hunting for the escaped prisoner.", "警方正在搜捕越狱囚犯。"),
    ("hut", "/hʌt/", "n.", "小屋；棚屋；临时营房", "They stayed in a wooden hut by the lake.", "他们住在湖边的一间木屋里。"),
    ("hybrid", "/ˈhaɪbrɪd/", "n./adj.", "杂交种；混合的；混合动力", "The car uses hybrid technology.", "这辆车使用混合动力技术。"),
    ("hydrogen", "/ˈhaɪdrədʒən/", "n.", "氢；氢气", "Water is composed of hydrogen and oxygen.", "水由氢和氧组成。"),
    ("hypothesis", "/haɪˈpɒθəsɪs/", "n.", "假说；假设；前提", "The scientist tested her hypothesis.", "科学家验证了她的假设。"),
    ("ideal", "/aɪˈdiːəl/", "adj./n.", "理想的；完美的；理想", "This is an ideal location for a picnic.", "这是一个理想的野餐地点。"),
    ("identical", "/aɪˈdentɪkl/", "adj.", "相同的；完全一样的", "The two pictures are almost identical.", "这两幅画几乎完全相同。"),
    ("identify", "/aɪˈdentɪfaɪ/", "v.", "识别；确认；鉴定", "Can you identify the person in this photo?", "你能认出这张照片中的人吗？"),
    ("identity", "/aɪˈdentəti/", "n.", "身份；特征；同一性", "He kept his identity secret.", "他隐藏了自己的身份。"),
    ("ideology", "/ˌaɪdiˈɒlədʒi/", "n.", "意识形态；思想体系", "The party is based on a socialist ideology.", "该政党基于社会主义意识形态。"),
    ("idiom", "/ˈɪdiəm/", "n.", "习语；成语；惯用语", "Learning idioms is important for fluency.", "学习习语对流利表达很重要。"),
    ("ignorance", "/ˈɪɡnərəns/", "n.", "无知；愚昧；不了解", "Ignorance is not an excuse.", "无知不是借口。"),
    ("illegal", "/ɪˈliːɡl/", "adj.", "非法的；违法的；违规的", "It is illegal to park here.", "在这里停车是违法的。"),
    ("illness", "/ˈɪlnəs/", "n.", "疾病；生病；不健康", "She missed school due to illness.", "她因病缺课。"),
    ("illusion", "/ɪˈluːʒn/", "n.", "错觉；幻觉；幻想", "The mirror creates an optical illusion.", "镜子制造了视觉错觉。"),
    ("illustrate", "/ˈɪləstreɪt/", "v.", "说明；阐明；配图", "The examples illustrate the point perfectly.", "这些例子完美地说明了这一点。"),
    ("image", "/ˈɪmɪdʒ/", "n.", "图像；形象；印象", "The company wants to improve its image.", "公司想改善形象。"),
    ("imaginary", "/ɪˈmædʒɪnəri/", "adj.", "想象的；虚构的；假想的", "The story is about an imaginary world.", "这个故事是关于一个想象的世界。"),
    ("imagination", "/ɪˌmædʒɪˈneɪʃn/", "n.", "想象力；创造力；幻想", "Children have vivid imaginations.", "孩子们有生动的想象力。"),
    ("imitate", "/ˈɪmɪteɪt/", "v.", "模仿；仿效；仿制", "The robot can imitate human movements.", "这个机器人能模仿人类动作。"),
    ("immature", "/ˌɪməˈtʃʊər/", "adj.", "不成熟的；幼稚的", "His behavior is immature for his age.", "他的行为对于他的年龄来说很不成熟。"),
    ("immediate", "/ɪˈmiːdiət/", "adj.", "立即的；直接的；紧迫的", "We need immediate action.", "我们需要立即行动。"),
    ("immense", "/ɪˈmens/", "adj.", "巨大的；极大的；无边的", "The project requires immense effort.", "这个项目需要巨大的努力。"),
    ("immigrant", "/ˈɪmɪɡrənt/", "n./adj.", "移民；侨民；移民的", "The city has many immigrant communities.", "这个城市有许多移民社区。"),
    ("immune", "/ɪˈmjuːn/", "adj.", "免疫的；不受影响的", "Vaccines help build immune defenses.", "疫苗有助于建立免疫防御。"),
    ("impact", "/ˈɪmpækt/", "n./v.", "影响；冲击；撞击", "The policy had a positive impact.", "该政策产生了积极的影响。"),
    ("impair", "/ɪmˈpeər/", "v.", "损害；削弱；损伤", "Lack of sleep can impair judgment.", "缺乏睡眠会损害判断力。"),
    ("impart", "/ɪmˈpɑːt/", "v.", "传授；赋予；告知", "Teachers impart knowledge to students.", "教师向学生传授知识。"),
    ("impatient", "/ɪmˈpeɪʃnt/", "adj.", "不耐烦的；急躁的；急切的", "He grew impatient with the delays.", "他对延误变得不耐烦。"),
    ("implement", "/ˈɪmplɪment/", "v./n.", "实施；执行；工具", "The plan needs to be implemented carefully.", "计划需要谨慎执行。"),
    ("implication", "/ˌɪmplɪˈkeɪʃn/", "n.", "含义；暗示；影响", "The implication of his statement was clear.", "他声明的含义很明确。"),
    ("implicit", "/ɪmˈplɪsɪt/", "adj.", "隐含的；暗示的；绝对的", "There was implicit trust between them.", "他们之间有着绝对的信任。"),
    ("import", "/ˈɪmpɔːt/", "v./n.", "进口；输入；重要性", "The country imports oil from abroad.", "该国从国外进口石油。"),
    ("impose", "/ɪmˈpəʊz/", "v.", "强加；征收；推行", "The government imposed new tariffs.", "政府征收了新关税。"),
    ("impress", "/ɪmˈpres/", "v.", "印；给...深刻印象", "She impressed everyone with her knowledge.", "她的知识给每个人留下了深刻印象。"),
    ("impression", "/ɪmˈpreʃn/", "n.", "印象；感想；印记", "First impressions are important.", "第一印象很重要。"),
    ("improvement", "/ɪmˈpruːvmənt/", "n.", "改进；改善；提高", "There has been a noticeable improvement.", "有了明显的改进。"),
    ("impulse", "/ˈɪmpʌls/", "n.", "冲动；推动；脉冲", "He acted on impulse.", "他一时冲动行事。"),
    ("inadequate", "/ɪnˈædɪkwət/", "adj.", "不充分的；不适当的", "The supply was inadequate for the demand.", "供不应求。"),
    ("inappropriate", "/ˌɪnəˈprəʊpriət/", "adj.", "不适当的；不合宜的", "His comment was inappropriate.", "他的评论不恰当。"),
    ("incentive", "/ɪnˈsentɪv/", "n.", "激励；刺激；诱因", "Financial incentives can improve performance.", "经济激励可以提高绩效。"),
    ("incident", "/ˈɪnsɪdənt/", "n.", "事件；事变；插曲", "The incident was captured on video.", "该事件被视频捕捉到了。"),
    ("incline", "/ɪnˈklaɪn/", "v./n.", "倾斜；倾向；斜坡", "I incline to disagree with you.", "我倾向于不同意你的观点。"),
    ("inclusive", "/ɪnˈkluːsɪv/", "adj.", "包括的；包容的；包含的", "The price is inclusive of tax.", "价格含税。"),
    ("incorporate", "/ɪnˈkɔːpəreɪt/", "v.", "合并；包含；组成公司", "The new design incorporates feedback from users.", "新设计吸收了用户的反馈。"),
    ("incredible", "/ɪnˈkredəbl/", "adj.", "难以置信的；极好的", "The view was incredible.", "景色美得令人难以置信。"),
    ("independence", "/ˌɪndɪˈpendəns/", "n.", "独立；自主；自立", "The country gained independence in 1947.", "该国于1947年获得独立。"),
    ("indicate", "/ˈɪndɪkeɪt/", "v.", "表明；指示；暗示", "The evidence indicates his guilt.", "证据表明他有罪。"),
    ("indifferent", "/ɪnˈdɪfrənt/", "adj.", "冷漠的；不关心的；中立的", "She seemed indifferent to his suffering.", "她似乎对他的痛苦漠不关心。"),
    ("indignant", "/ɪnˈdɪɡnənt/", "adj.", "愤慨的；愤怒的；义愤的", "He was indignant at the unfair treatment.", "他对这种不公平待遇感到愤慨。"),
    ("indispensable", "/ˌɪndɪˈspensəbl/", "adj.", "必不可少的；必需的", "Water is indispensable for life.", "水对生命是必不可少的。"),
    ("individual", "/ˌɪndɪˈvɪdʒuəl/", "adj./n.", "个人的；单独的；个人", "Each individual has unique talents.", "每个人都有独特的才能。"),
    ("induce", "/ɪnˈdjuːs/", "v.", "引诱；引起；劝使", "The drug induces sleep.", "这种药会引人入睡。"),
    ("industrial", "/ɪnˈdʌstriəl/", "adj.", "工业的；产业的；产业的", "The industrial revolution changed the world.", "工业革命改变了世界。"),
    ("inevitable", "/ɪnˈevɪtəbl/", "adj.", "不可避免的；必然的", "Change is inevitable.", "变化是不可避免的。"),
    ("infant", "/ˈɪnfənt/", "n./adj.", "婴儿；幼儿；初期的", "The infant is only three months old.", "这个婴儿只有三个月大。"),
    ("infect", "/ɪnˈfekt/", "v.", "感染；传染；影响", "The virus infects millions each year.", "这种病毒每年感染数百万人。"),
    ("infer", "/ɪnˈfɜːr/", "v.", "推断；推论；猜想", "What can we infer from the evidence?", "我们能从证据中推断出什么？"),
    ("infinite", "/ˈɪnfɪnət/", "adj.", "无限的；无穷的；极大的", "The possibilities are infinite.", "可能性是无限的。"),
    ("inflation", "/ɪnˈfleɪʃn/", "n.", "通货膨胀；膨胀", "Inflation is rising across the country.", "全国通货膨胀正在上升。"),
    ("influence", "/ˈɪnfluəns/", "n./v.", "影响；势力；感化", "Social media has a strong influence on youth.", "社交媒体对年轻人有很大影响。"),
    ("inform", "/ɪnˈfɔːm/", "v.", "通知；告知；报告", "Please inform us of your decision.", "请通知我们你的决定。"),
    ("ingredient", "/ɪnˈɡriːdiənt/", "n.", "成分；原料；因素", "Flour is a basic ingredient for bread.", "面粉是面包的基本原料。"),
    ("inhabit", "/ɪnˈhæbɪt/", "v.", "居住于；栖息于；占据", "Many species inhabit the rainforest.", "许多物种栖息在雨林中。"),
    ("inherit", "/ɪnˈherɪt/", "v.", "继承；经遗传获得", "She inherited the property from her father.", "她从父亲那里继承了财产。"),
    ("initial", "/ɪˈnɪʃl/", "adj./n.", "最初的；开始的；首字母", "The initial results are promising.", "初步结果很有希望。"),
    ("initiate", "/ɪˈnɪʃieɪt/", "v.", "开始；发起；接纳", "The government initiated a new program.", "政府启动了一个新项目。"),
    ("inject", "/ɪnˈdʒekt/", "v.", "注射；注入；引入", "The doctor injected the vaccine.", "医生注射了疫苗。"),
    ("injure", "/ˈɪndʒər/", "v.", "伤害；损伤；损害", "He was injured in the accident.", "他在事故中受伤了。"),
    ("innocent", "/ˈɪnəsnt/", "adj.", "无辜的；清白的；天真的", "The jury found him innocent.", "陪审团判他无罪。"),
    ("innovation", "/ˌɪnəˈveɪʃn/", "n.", "创新；革新；新方法", "Innovation drives economic growth.", "创新驱动经济增长。"),
    ("input", "/ˈɪnpʊt/", "n./v.", "输入；投入；输入信息", "We need more input from users.", "我们需要更多用户输入。"),
    ("inquiry", "/ɪnˈkwaɪəri/", "n.", "询问；调查；探究", "The police launched an inquiry into the matter.", "警方对此事展开了调查。"),
    ("insight", "/ˈɪnsaɪt/", "n.", "洞察力；洞悉；深刻见解", "The article provides valuable insights.", "这篇文章提供了宝贵的见解。"),
    ("inspect", "/ɪnˈspekt/", "v.", "检查；检验；审视", "The building was inspected for safety.", "大楼接受了安全检查。"),
    ("inspiration", "/ˌɪnspəˈreɪʃn/", "n.", "灵感；鼓舞；启发", "Nature is a great source of inspiration.", "大自然是灵感的巨大源泉。"),
    ("install", "/ɪnˈstɔːl/", "v.", "安装；安置；就职", "We need to install the new software.", "我们需要安装新软件。"),
    ("instant", "/ˈɪnstənt/", "adj./n.", "立即的；速食的；瞬间", "The message was delivered in an instant.", "消息瞬间就送达了。"),
    ("instinct", "/ˈɪnstɪŋkt/", "n.", "本能；直觉；天性", "Birds migrate by instinct.", "鸟类凭本能迁徙。"),
    ("institute", "/ˈɪnstɪtjuːt/", "n./v.", "学院；研究所；建立", "She works at a research institute.", "她在一家研究所工作。"),
    ("instruct", "/ɪnˈstrʌkt/", "v.", "指导；指示；教授", "The manual instructs users on setup.", "手册指导用户如何安装。"),
    ("instrument", "/ˈɪnstrəmənt/", "n.", "工具；仪器；乐器", "He plays several musical instruments.", "他会演奏几种乐器。"),
    ("insurance", "/ɪnˈʃʊərəns/", "n.", "保险；保险费；保障", "Health insurance is very important.", "健康保险非常重要。"),
    ("intact", "/ɪnˈtækt/", "adj.", "完整的；完好无损的", "The building survived the earthquake intact.", "这座建筑在地震中完好无损。"),
    ("integrate", "/ˈɪntɪɡreɪt/", "v.", "整合；合并；融入", "The new system integrates all functions.", "新系统整合了所有功能。"),
    ("intellectual", "/ˌɪntəˈlektʃuəl/", "adj./n.", "智力的；知识的；知识分子", "She comes from an intellectual family.", "她出身于知识分子家庭。"),
    ("intelligence", "/ɪnˈtelɪdʒəns/", "n.", "智力；智慧；情报", "Artificial intelligence is transforming industries.", "人工智能正在改变各行各业。"),
    ("intend", "/ɪnˈtend/", "v.", "打算；计划；意图", "What do you intend to do after graduation?", "你毕业后打算做什么？"),
    ("intense", "/ɪnˈtens/", "adj.", "强烈的；紧张的；激烈的", "The competition was intense.", "竞争非常激烈。"),
    ("interact", "/ˌɪntərˈækt/", "v.", "互动；相互作用；交流", "Students should interact with each other.", "学生应该互相交流。"),
    ("interfere", "/ˌɪntəˈfɪər/", "v.", "干涉；干预；妨碍", "Dont interfere in other peoples affairs.", "不要干涉别人的事。"),
    ("interior", "/ɪnˈtɪəriər/", "n./adj.", "内部；内陆；内部的", "The interior of the house is beautifully decorated.", "房子内部装修精美。"),
    ("interpret", "/ɪnˈtɜːprɪt/", "v.", "解释；说明；口译", "How do you interpret this data?", "你如何解释这些数据？"),
    ("interrupt", "/ˌɪntəˈrʌpt/", "v.", "打断；中断；打扰", "Please dont interrupt me.", "请不要打断我。"),
    ("interval", "/ˈɪntəvl/", "n.", "间隔；休息时间；音程", "The buses run at 15-minute intervals.", "公交车每15分钟一班。"),
    ("intervene", "/ˌɪntəˈviːn/", "v.", "干预；介入；调停", "The government intervened to stabilize the economy.", "政府干预以稳定经济。"),
    ("intimate", "/ˈɪntɪmət/", "adj./v.", "亲密的；私密的；暗示", "They are intimate friends.", "他们是亲密的朋友。"),
    ("intimidate", "/ɪnˈtɪmɪdeɪt/", "v.", "恐吓；威胁；胁迫", "He tried to intimidate the witness.", "他试图恐吓证人。"),
    ("invade", "/ɪnˈveɪd/", "v.", "侵略；侵犯；入侵", "The army invaded the neighboring country.", "军队入侵了邻国。"),
    ("investigate", "/ɪnˈvestɪɡeɪt/", "v.", "调查；研究；侦查", "The police are investigating the crime.", "警方正在调查这起犯罪。"),
    ("investment", "/ɪnˈvestmənt/", "n.", "投资；投入；投资额", "Education is a good investment.", "教育是一项很好的投资。"),
    ("invisible", "/ɪnˈvɪzəbl/", "adj.", "看不见的；无形的；隐形的", "The bacteria are invisible to the naked eye.", "细菌肉眼看不见。"),
    ("involve", "/ɪnˈvɒlv/", "v.", "涉及；包含；使参与", "The project involves many people.", "这个项目涉及许多人。"),
    ("isolate", "/ˈaɪsəleɪt/", "v.", "隔离；孤立；分离", "The patient was isolated to prevent infection.", "病人被隔离以防感染。"),
    ("issue", "/ˈɪʃuː/", "n./v.", "问题；议题；发行；发布", "We need to address this issue urgently.", "我们需要紧急处理这个问题。"),
    ("item", "/ˈaɪtəm/", "n.", "项目；条款；物品", "Please check each item on the list.", "请核对清单上的每个项目。"),
]
