# High-frequency words C-E
HIGH_WORDS_B = [
    ("calculate", "/ˈkælkjuleɪt/", "v.", "计算；推算", "We need to calculate the total cost.", "我们需要计算总成本。"),
    ("campaign", "/kæmˈpeɪn/", "n./v.", "运动；战役；竞选活动", "They launched a campaign to raise funds.", "他们发起了筹款活动。"),
    ("capacity", "/kəˈpæsəti/", "n.", "容量；能力；资格", "The hall has a seating capacity of 2000.", "这个大厅可容纳2000人。"),
    ("capture", "/ˈkæptʃər/", "v./n.", "捕获；夺取；引起", "The photographer captured the beauty of nature.", "摄影师捕捉到了自然之美。"),
    ("career", "/kəˈrɪər/", "n.", "生涯；职业", "She chose a career in medicine.", "她选择了医学事业。"),
    ("category", "/ˈkætəɡəri/", "n.", "类别；种类", "The books are organized by category.", "书籍按类别整理。"),
    ("cause", "/kɔːz/", "v./n.", "引起；原因；事业", "The accident caused serious damage.", "事故造成了严重损失。"),
    ("cease", "/siːs/", "v.", "停止；终止", "The company has ceased operations.", "该公司已停止运营。"),
    ("celebrate", "/ˈselɪbreɪt/", "v.", "庆祝；颂扬", "We celebrated her promotion with a party.", "我们举办派对庆祝她的晋升。"),
    ("challenge", "/ˈtʃælɪndʒ/", "n./v.", "挑战；质疑", "Learning a new language is a challenge.", "学习一门新语言是一个挑战。"),
    ("characteristic", "/ˌkærəktəˈrɪstɪk/", "adj./n.", "特有的；特征", "The characteristic of this species is unique.", "这个物种的特征是独特的。"),
    ("charity", "/ˈtʃærəti/", "n.", "慈善；慈善机构", "He donated a large sum to charity.", "他向慈善机构捐了一大笔钱。"),
    ("circumstance", "/ˈsɜːkəmstəns/", "n.", "环境；情况；境况", "Under no circumstances should you lie.", "在任何情况下你都不应该说谎。"),
    ("claim", "/kleɪm/", "v./n.", "声称；要求；索赔", "He claimed that he saw the accident.", "他声称看到了事故。"),
    ("clarify", "/ˈklærəfaɪ/", "v.", "澄清；阐明", "Could you clarify your point?", "你能澄清一下你的观点吗？"),
    ("classic", "/ˈklæsɪk/", "adj./n.", "经典的；一流的", "This novel is a classic of English literature.", "这部小说是英国文学的经典作品。"),
    ("collapse", "/kəˈlæps/", "v./n.", "倒塌；崩溃；瓦解", "The building collapsed in the earthquake.", "建筑物在地震中倒塌了。"),
    ("colleague", "/ˈkɒliːɡ/", "n.", "同事；同僚", "I discussed the project with my colleagues.", "我和同事们讨论了项目。"),
    ("command", "/kəˈmɑːnd/", "v./n.", "命令；指挥；掌握", "The general commanded his troops to advance.", "将军命令部队前进。"),
    ("commence", "/kəˈmens/", "v.", "开始；着手", "The ceremony will commence at 9 am.", "仪式将在上午9点开始。"),
    ("comment", "/ˈkɒment/", "n./v.", "评论；意见", "Please leave your comments below.", "请在下面留下你的评论。"),
    ("commerce", "/ˈkɒmɜːs/", "n.", "商业；贸易", "The city is a center of commerce.", "这个城市是商业中心。"),
    ("commit", "/kəˈmɪt/", "v.", "犯（罪）；承诺；致力于", "She committed herself to helping others.", "她致力于帮助他人。"),
    ("communicate", "/kəˈmjuːnɪkeɪt/", "v.", "交流；沟通；传播", "We communicate via email every day.", "我们每天通过电子邮件沟通。"),
    ("community", "/kəˈmjuːnəti/", "n.", "社区；团体；共同体", "The local community supported the project.", "当地社区支持了这个项目。"),
    ("companion", "/kəmˈpæniən/", "n.", "同伴；伙伴", "Dogs are loyal companions.", "狗是忠诚的伙伴。"),
    ("compare", "/kəmˈpeər/", "v.", "比较；对比", "Compared to last year, sales have improved.", "与去年相比，销售额有所提高。"),
    ("compel", "/kəmˈpel/", "v.", "强迫；迫使", "The law compels companies to follow safety standards.", "法律迫使公司遵守安全标准。"),
    ("compensate", "/ˈkɒmpenseɪt/", "v.", "补偿；赔偿", "The company compensated workers for the injury.", "公司赔偿了工人的伤害。"),
    ("compete", "/kəmˈpiːt/", "v.", "竞争；比赛", "Small businesses cannot compete with large corporations.", "小企业无法与大公司竞争。"),
    ("complain", "/kəmˈpleɪn/", "v.", "抱怨；投诉", "Customers complained about the poor service.", "顾客投诉服务质量差。"),
    ("complete", "/kəmˈpliːt/", "adj./v.", "完整的；完成", "The project is now complete.", "项目现已完成。"),
    ("complex", "/ˈkɒmpleks/", "adj./n.", "复杂的；综合体", "The problem is more complex than it appears.", "这个问题比看起来更复杂。"),
    ("complicate", "/ˈkɒmplɪkeɪt/", "v.", "使复杂化；使难办", "Dont complicate things unnecessarily.", "不要不必要地使事情复杂化。"),
    ("component", "/kəmˈpəʊnənt/", "n.", "成分；组成部分", "Each component of the system must function properly.", "系统的每个组成部分都必须正常运行。"),
    ("compose", "/kəmˈpəʊz/", "v.", "组成；创作；作曲", "The committee is composed of experts.", "委员会由专家组成。"),
    ("comprehend", "/ˌkɒmprɪˈhend/", "v.", "理解；领悟", "Its difficult to comprehend the scale of the universe.", "很难理解宇宙的规模。"),
    ("comprehensive", "/ˌkɒmprɪˈhensɪv/", "adj.", "全面的；综合的", "We provide comprehensive training for new employees.", "我们为新员工提供全面培训。"),
    ("comprise", "/kəmˈpraɪz/", "v.", "包括；由...组成", "The book comprises twelve chapters.", "这本书包括十二章。"),
    ("compromise", "/ˈkɒmprəmaɪz/", "v./n.", "妥协；折中；损害", "Both sides need to reach a compromise.", "双方需要达成妥协。"),
    ("conceal", "/kənˈsiːl/", "v.", "隐藏；隐瞒", "She tried to conceal her disappointment.", "她试图掩饰自己的失望。"),
    ("concentrate", "/ˈkɒnsəntreɪt/", "v.", "集中；专注；浓缩", "I need to concentrate on my studies.", "我需要专注于学习。"),
    ("concept", "/ˈkɒnsept/", "n.", "概念；观念", "This concept is difficult to grasp.", "这个概念很难理解。"),
    ("concern", "/kənˈsɜːn/", "v./n.", "涉及；关心；担忧", "The report concerns environmental issues.", "这份报告涉及环境问题。"),
    ("conclude", "/kənˈkluːd/", "v.", "结束；得出结论；推断", "What can we conclude from this data?", "我们能从这些数据中得出什么结论？"),
    ("concrete", "/ˈkɒŋkriːt/", "adj./n.", "具体的；混凝土", "We need concrete evidence to support our claim.", "我们需要具体证据来支持我们的主张。"),
    ("condemn", "/kənˈdem/", "v.", "谴责；判刑", "The international community condemned the violence.", "国际社会谴责了暴力行为。"),
    ("condition", "/kənˈdɪʃn/", "n./v.", "条件；状况；训练", "The car is in good condition.", "这辆车状况良好。"),
    ("conduct", "/kənˈdʌkt/", "v./n.", "进行；指导；行为", "The scientist conducted several experiments.", "科学家进行了多次实验。"),
    ("conference", "/ˈkɒnfərəns/", "n.", "会议；讨论会", "She is attending a conference on climate change.", "她正在参加一个气候变化会议。"),
    ("confidence", "/ˈkɒnfɪdəns/", "n.", "信心；自信；信任", "You need to have confidence in your abilities.", "你需要对自己的能力有信心。"),
    ("confirm", "/kənˈfɜːm/", "v.", "确认；证实；批准", "Please confirm your reservation by email.", "请通过电子邮件确认你的预订。"),
    ("conflict", "/ˈkɒnflɪkt/", "n./v.", "冲突；矛盾；斗争", "The two countries are in conflict.", "这两个国家处于冲突中。"),
    ("confront", "/kənˈfrʌnt/", "v.", "面对；遭遇；对抗", "We must confront the challenges ahead.", "我们必须面对前方的挑战。"),
    ("conscious", "/ˈkɒnʃəs/", "adj.", "有意识的；清醒的；自觉的", "She was conscious of the risks involved.", "她意识到了其中的风险。"),
    ("consequence", "/ˈkɒnsɪkwəns/", "n.", "结果；后果；重要性", "Every action has consequences.", "每个行为都有后果。"),
    ("conservation", "/ˌkɒnsəˈveɪʃn/", "n.", "保存；保护；守恒", "Wildlife conservation is important for biodiversity.", "野生动物保护对生物多样性很重要。"),
    ("consider", "/kənˈsɪdər/", "v.", "考虑；认为；体谅", "Please consider my application carefully.", "请仔细考虑我的申请。"),
    ("consistent", "/kənˈsɪstənt/", "adj.", "一致的；连贯的；相符的", "His actions are consistent with his words.", "他的言行一致。"),
    ("constitute", "/ˈkɒnstɪtjuːt/", "v.", "组成；构成；设立", "Twelve months constitute a year.", "十二个月构成一年。"),
    ("construct", "/kənˈstrʌkt/", "v./n.", "建造；构造；构思", "They plan to construct a new bridge.", "他们计划建造一座新桥。"),
    ("consume", "/kənˈsjuːm/", "v.", "消费；消耗；消灭", "The car consumes a lot of fuel.", "这辆车消耗很多燃料。"),
    ("contact", "/ˈkɒntækt/", "n./v.", "接触；联系；交往", "Please contact me if you have any questions.", "如有问题请与我联系。"),
    ("contain", "/kənˈteɪn/", "v.", "包含；容纳；控制", "This box contains fragile items.", "这个盒子装有易碎物品。"),
    ("contemporary", "/kənˈtemprəri/", "adj./n.", "当代的；同时代的", "She is an expert in contemporary art.", "她是当代艺术专家。"),
    ("content", "/ˈkɒntent/", "n./adj.", "内容；含量；满意的", "The content of the article is very informative.", "这篇文章的内容信息量很大。"),
    ("contest", "/ˈkɒntest/", "n./v.", "比赛；竞赛；争夺", "She won first prize in the speech contest.", "她在演讲比赛中获得了一等奖。"),
    ("continue", "/kənˈtɪnjuː/", "v.", "继续；延续；持续", "The rain continued for three days.", "雨持续了三天。"),
    ("contract", "/ˈkɒntrækt/", "n./v.", "合同；契约；收缩", "Sign the contract before starting work.", "开始工作前先签合同。"),
    ("contradict", "/ˌkɒntrəˈdɪkt/", "v.", "与...矛盾；反驳", "His statement contradicts the evidence.", "他的说法与证据相矛盾。"),
    ("contrary", "/ˈkɒntrəri/", "adj./n.", "相反的；对立面", "Contrary to popular belief, he is very kind.", "与普遍看法相反，他非常和蔼。"),
    ("contribute", "/kənˈtrɪbjuːt/", "v.", "贡献；捐助；促成", "Everyone should contribute to the team.", "每个人都应该为团队做贡献。"),
    ("controversy", "/ˈkɒntrəvɜːsi/", "n.", "争论；争议；论战", "The decision caused a lot of controversy.", "这个决定引发了很大争议。"),
    ("convenient", "/kənˈviːniənt/", "adj.", "方便的；便利的", "Online shopping is very convenient.", "网上购物非常方便。"),
    ("convention", "/kənˈvenʃn/", "n.", "惯例；常规；大会", "Its just a social convention.", "这只是社会惯例。"),
    ("convince", "/kənˈvɪns/", "v.", "说服；使确信", "I finally convinced her to join us.", "我终于说服她和我们一起去。"),
    ("cooperate", "/kəʊˈɒpəreɪt/", "v.", "合作；协作；配合", "The two companies agreed to cooperate.", "两家公司同意合作。"),
    ("coordinate", "/kəʊˈɔːdɪneɪt/", "v./adj.", "协调；调整；同等的", "We need to coordinate our efforts.", "我们需要协调我们的努力。"),
    ("cope", "/kəʊp/", "v.", "应对；处理；对付", "She learned to cope with stress.", "她学会了应对压力。"),
    ("correspond", "/ˌkɒrɪˈspɒnd/", "v.", "对应；通信；相符", "The numbers correspond to specific items.", "这些数字对应特定项目。"),
    ("counsel", "/ˈkaʊnsl/", "n./v.", "咨询；建议；律师", "She sought counsel from a professional.", "她向专业人士寻求建议。"),
    ("creative", "/kriˈeɪtɪv/", "adj.", "创造性的；有创意的", "She has a very creative mind.", "她非常有创意。"),
    ("critical", "/ˈkrɪtɪkl/", "adj.", "批评的；关键的；危急的", "This is a critical moment in the negotiations.", "这是谈判的关键时刻。"),
    ("cultivate", "/ˈkʌltɪveɪt/", "v.", "培养；耕作；陶冶", "You should cultivate good study habits.", "你应该培养良好的学习习惯。"),
    ("curiosity", "/ˌkjʊəriˈɒsəti/", "n.", "好奇；好奇心；珍品", "Children are full of curiosity.", "孩子们充满好奇心。"),
    ("currency", "/ˈkʌrənsi/", "n.", "货币；流通；流行", "The dollar is a strong currency.", "美元是强势货币。"),
    ("current", "/ˈkʌrənt/", "adj./n.", "当前的；流动；电流", "What is the current situation?", "目前的情况如何？"),
    ("curriculum", "/kəˈrɪkjələm/", "n.", "课程；课程表", "The curriculum has been updated.", "课程已更新。"),
    ("custom", "/ˈkʌstəm/", "n./adj.", "习俗；习惯；定制的", "Its a local custom to greet everyone.", "问候每个人是当地的习俗。"),
]
