# High-frequency words D-F
HIGH_WORDS_C = [
    ("damage", "/ˈdæmɪdʒ/", "n./v.", "损害；损伤；损失", "The storm caused extensive damage.", "暴风雨造成了广泛的破坏。"),
    ("debate", "/dɪˈbeɪt/", "n./v.", "辩论；争论；讨论", "There was a heated debate on the issue.", "关于这个问题有激烈的辩论。"),
    ("debt", "/det/", "n.", "债务；欠款", "The company is heavily in debt.", "这家公司负债累累。"),
    ("decade", "/ˈdekeɪd/", "n.", "十年；十年期", "Technology has advanced rapidly in the past decade.", "过去十年技术进步迅速。"),
    ("deceive", "/dɪˈsiːv/", "v.", "欺骗；蒙蔽", "Do not be deceived by appearances.", "不要被外表所欺骗。"),
    ("decent", "/ˈdiːsnt/", "adj.", "体面的；像样的；正派的", "Everyone deserves a decent job.", "每个人都应该有一份体面的工作。"),
    ("decisive", "/dɪˈsaɪsɪv/", "adj.", "决定性的；果断的", "The battle was a decisive victory.", "这场战役是决定性的胜利。"),
    ("declare", "/dɪˈkleər/", "v.", "宣布；声明；申报", "The government declared a state of emergency.", "政府宣布进入紧急状态。"),
    ("decline", "/dɪˈklaɪn/", "v./n.", "下降；衰退；拒绝", "The population of the village has declined.", "这个村庄的人口减少了。"),
    ("decrease", "/dɪˈkriːs/", "v./n.", "减少；减小；降低", "Sales decreased by 10% this month.", "本月销售额下降了10%。"),
    ("dedicate", "/ˈdedɪkeɪt/", "v.", "致力于；奉献；题献", "She dedicated her life to education.", "她将一生奉献给了教育。"),
    ("defeat", "/dɪˈfiːt/", "v./n.", "打败；击败；失败", "The team suffered a heavy defeat.", "该队遭受了惨败。"),
    ("defend", "/dɪˈfend/", "v.", "防御；保护；辩护", "Soldiers defend the country from attack.", "士兵保卫国家免受攻击。"),
    ("deficit", "/ˈdefɪsɪt/", "n.", "赤字；逆差；不足", "The budget deficit continues to grow.", "预算赤字继续增长。"),
    ("define", "/dɪˈfaɪn/", "v.", "定义；界定；明确", "How do you define success?", "你如何定义成功？"),
    ("definite", "/ˈdefɪnət/", "adj.", "明确的；确定的", "We need a definite answer by Friday.", "我们需要在周五前得到明确答复。"),
    ("degree", "/dɪˈɡriː/", "n.", "程度；学位；度数", "She earned a degree in economics.", "她获得了经济学学位。"),
    ("delay", "/dɪˈleɪ/", "v./n.", "延迟；推迟；延误", "The flight was delayed due to bad weather.", "航班因天气恶劣延误了。"),
    ("deliberate", "/dɪˈlɪbərət/", "adj./v.", "故意的；深思熟虑的", "It was a deliberate act of provocation.", "这是故意的挑衅行为。"),
    ("delicate", "/ˈdelɪkət/", "adj.", "精致的；微妙的；脆弱的", "The negotiations are at a delicate stage.", "谈判处于微妙阶段。"),
    ("deliver", "/dɪˈlɪvər/", "v.", "递送；发表；交付", "He delivered an inspiring speech.", "他发表了鼓舞人心的演讲。"),
    ("demand", "/dɪˈmɑːnd/", "v./n.", "要求；需求；需要", "There is high demand for skilled workers.", "对熟练工人的需求很高。"),
    ("demonstrate", "/ˈdemənstreɪt/", "v.", "证明；展示；示威", "The experiment demonstrates the principle clearly.", "这个实验清楚地展示了原理。"),
    ("deny", "/dɪˈnaɪ/", "v.", "否认；拒绝；剥夺", "He denied any involvement in the crime.", "他否认参与该犯罪。"),
    ("depart", "/dɪˈpɑːt/", "v.", "离开；出发；背离", "The train departs at 6 pm.", "火车下午6点出发。"),
    ("depend", "/dɪˈpend/", "v.", "依赖；依靠；取决于", "Success depends on hard work.", "成功取决于努力工作。"),
    ("depict", "/dɪˈpɪkt/", "v.", "描绘；描述；刻画", "The painting depicts a peaceful landscape.", "这幅画描绘了宁静的风景。"),
    ("deposit", "/dɪˈpɒzɪt/", "v./n.", "存放；存款；押金", "You need to pay a deposit to reserve the room.", "你需要付押金来预订房间。"),
    ("depress", "/dɪˈpres/", "v.", "使沮丧；使萧条；压下", "The bad news depressed everyone.", "坏消息让每个人都感到沮丧。"),
    ("derive", "/dɪˈraɪv/", "v.", "源自；获得；推导", "The word derives from Latin.", "这个词源自拉丁语。"),
    ("describe", "/dɪˈskraɪb/", "v.", "描述；形容；描绘", "Can you describe what happened?", "你能描述发生了什么吗？"),
    ("deserve", "/dɪˈzɜːv/", "v.", "应得；值得", "You deserve a promotion after all your hard work.", "你的辛勤工作值得晋升。"),
    ("design", "/dɪˈzaɪn/", "v./n.", "设计；图案；意图", "She designed the new product line.", "她设计了新的产品线。"),
    ("desperate", "/ˈdespərət/", "adj.", "绝望的；不顾一切的；拼命的", "They were desperate for help.", "他们非常渴望得到帮助。"),
    ("despite", "/dɪˈspaɪt/", "prep.", "尽管；不管；任凭", "Despite the rain, they continued playing.", "尽管下雨，他们还是继续玩耍。"),
    ("destination", "/ˌdestɪˈneɪʃn/", "n.", "目的地；终点", "We finally reached our destination.", "我们终于到达了目的地。"),
    ("destroy", "/dɪˈstrɔɪ/", "v.", "破坏；摧毁；消灭", "The earthquake destroyed many buildings.", "地震摧毁了许多建筑。"),
    ("detect", "/dɪˈtekt/", "v.", "察觉；发现；探测", "The device can detect early signs of disease.", "这设备能检测疾病的早期迹象。"),
    ("determine", "/dɪˈtɜːmɪn/", "v.", "确定；决定；下决心", "We need to determine the cause of the problem.", "我们需要确定问题的原因。"),
    ("develop", "/dɪˈveləp/", "v.", "发展；开发；成长", "The company developed a new software.", "该公司开发了一款新软件。"),
    ("device", "/dɪˈvaɪs/", "n.", "设备；装置；策略", "This device measures air quality.", "这个设备测量空气质量。"),
    ("devote", "/dɪˈvəʊt/", "v.", "致力于；奉献；把...用于", "She devoted herself to scientific research.", "她致力于科学研究。"),
    ("diagnose", "/ˈdaɪəɡnəʊz/", "v.", "诊断；判断", "The doctor diagnosed the illness early.", "医生及早诊断了这种疾病。"),
    ("dignity", "/ˈdɪɡnəti/", "n.", "尊严；高贵；庄严", "Everyone should be treated with dignity.", "每个人都应该受到有尊严的对待。"),
    ("dilemma", "/dɪˈlemə/", "n.", "困境；两难", "She faced a moral dilemma.", "她面临道德困境。"),
    ("dimension", "/daɪˈmenʃn/", "n.", "维度；尺寸；方面", "We need to consider all dimensions of the problem.", "我们需要考虑问题的所有方面。"),
    ("diminish", "/dɪˈmɪnɪʃ/", "v.", "减少；缩小；贬低", "The pain will diminish over time.", "疼痛会随着时间减轻。"),
    ("diplomat", "/ˈdɪpləmæt/", "n.", "外交官；有外交手腕的人", "He served as a diplomat in several countries.", "他在多个国家担任过外交官。"),
    ("disaster", "/dɪˈzɑːstər/", "n.", "灾难；灾祸", "The flood was a terrible disaster.", "洪水是一场可怕的灾难。"),
    ("discipline", "/ˈdɪsəplɪn/", "n./v.", "纪律；学科；训练", "Learning a language requires discipline.", "学习语言需要自律。"),
    ("disclose", "/dɪsˈkləʊz/", "v.", "揭露；泄露；公开", "The company disclosed its financial results.", "公司公开了财务结果。"),
    ("discount", "/ˈdɪskaʊnt/", "n./v.", "折扣；贴现；不重视", "Students get a discount on tickets.", "学生购票有折扣。"),
    ("discourage", "/dɪˈskʌrɪdʒ/", "v.", "使气馁；阻碍；劝阻", "Dont let failure discourage you.", "不要因失败而气馁。"),
    ("discriminate", "/dɪˈskrɪmɪneɪt/", "v.", "歧视；区别对待", "It is illegal to discriminate against anyone.", "歧视任何人是违法的。"),
    ("disguise", "/dɪsˈɡaɪz/", "v./n.", "伪装；掩饰；假扮", "He disguised himself as a waiter.", "他伪装成服务员。"),
    ("dismiss", "/dɪsˈmɪs/", "v.", "解雇；驳回；解散", "The manager dismissed the employee.", "经理解雇了这名员工。"),
    ("display", "/dɪˈspleɪ/", "v./n.", "展示；陈列；表现", "The museum displays ancient artifacts.", "博物馆展示古代文物。"),
    ("dispose", "/dɪˈspəʊz/", "v.", "处理；安排；处置", "Please dispose of waste properly.", "请妥善处理垃圾。"),
    ("dispute", "/dɪˈspjuːt/", "n./v.", "争论；纠纷；质疑", "The workers are in dispute with management.", "工人与管理层存在纠纷。"),
    ("dissolve", "/dɪˈzɒlv/", "v.", "溶解；解散；消散", "Sugar dissolves in water.", "糖溶于水。"),
    ("distinguish", "/dɪˈstɪŋɡwɪʃ/", "v.", "区分；辨别；使杰出", "It is hard to distinguish the twins.", "很难区分这对双胞胎。"),
    ("distort", "/dɪˈstɔːt/", "v.", "扭曲；歪曲；变形", "The media distorted the facts.", "媒体歪曲了事实。"),
    ("distract", "/dɪˈstrækt/", "v.", "分散注意力；使分心", "Dont let your phone distract you from studying.", "不要让手机分散你学习的注意力。"),
    ("distribute", "/dɪˈstrɪbjuːt/", "v.", "分配；分发；散布", "The charity distributed food to the poor.", "慈善机构向穷人分发食物。"),
    ("disturb", "/dɪˈstɜːb/", "v.", "打扰；扰乱；使不安", "Please do not disturb me while Im working.", "我工作时请不要打扰。"),
    ("diverse", "/daɪˈvɜːs/", "adj.", "不同的；多样的；多元的", "The city has a diverse population.", "这个城市有多元化的人口。"),
    ("document", "/ˈdɒkjumənt/", "n./v.", "文件；文档；记录", "Please sign the document.", "请签署这份文件。"),
    ("domestic", "/dəˈmestɪk/", "adj.", "国内的；家庭的；驯养的", "The product is for domestic market only.", "该产品仅供国内市场。"),
    ("dominate", "/ˈdɒmɪneɪt/", "v.", "支配；主宰；在...中占优势", "The team dominated the game from start to finish.", "该队从头到尾主宰了比赛。"),
    ("donate", "/dəʊˈneɪt/", "v.", "捐赠；捐献", "Many people donated money to the cause.", "许多人为此事业捐款。"),
    ("dramatic", "/drəˈmætɪk/", "adj.", "戏剧性的；巨大的；引人注目的", "There has been a dramatic increase in sales.", "销售额有了戏剧性的增长。"),
    ("durable", "/ˈdjʊərəbl/", "adj.", "耐用的；持久的", "This material is very durable.", "这种材料非常耐用。"),
    ("dynamic", "/daɪˈnæmɪk/", "adj./n.", "动态的；有活力的；动力", "The team has a dynamic leader.", "这个团队有一位充满活力的领导。"),
    ("earnest", "/ˈɜːnɪst/", "adj.", "认真的；诚挚的；重要的", "He is an earnest young man.", "他是个认真的年轻人。"),
    ("ease", "/iːz/", "n./v.", "舒适；容易；减轻", "The medicine eased her pain.", "药物减轻了她的疼痛。"),
    ("economic", "/ˌiːkəˈnɒmɪk/", "adj.", "经济的；经济学的", "The country is facing economic challenges.", "该国面临经济挑战。"),
    ("economy", "/ɪˈkɒnəmi/", "n.", "经济；节约；理财", "The economy is growing steadily.", "经济正在稳步增长。"),
    ("educate", "/ˈedʒukeɪt/", "v.", "教育；培养；训练", "We need to educate children about the environment.", "我们需要教育孩子关于环境的知识。"),
    ("effective", "/ɪˈfektɪv/", "adj.", "有效的；生效的；实际的", "The new medicine is very effective.", "新药非常有效。"),
    ("efficiency", "/ɪˈfɪʃnsi/", "n.", "效率；效能；功效", "We need to improve our work efficiency.", "我们需要提高工作效率。"),
    ("elaborate", "/ɪˈlæbərət/", "adj./v.", "精心制作的；详细阐述", "Could you elaborate on your proposal?", "你能详细说明你的提议吗？"),
    ("elect", "/ɪˈlekt/", "v./adj.", "选举；推选；选中的", "They elected her as president.", "他们选举她为会长。"),
    ("elegant", "/ˈelɪɡənt/", "adj.", "优雅的；精致的；简洁的", "She wore an elegant dress.", "她穿着优雅的连衣裙。"),
    ("element", "/ˈelɪmənt/", "n.", "元素；要素；成分", "Hard work is a key element of success.", "努力是成功的关键要素。"),
    ("eliminate", "/ɪˈlɪmɪneɪt/", "v.", "消除；淘汰；消灭", "We need to eliminate all errors.", "我们需要消除所有错误。"),
    ("embrace", "/ɪmˈbreɪs/", "v./n.", "拥抱；包含；欣然接受", "She embraced the opportunity to study abroad.", "她欣然接受了出国留学的机会。"),
    ("emerge", "/ɪˈmɜːdʒ/", "v.", "出现；浮现；显露", "New evidence has emerged in the case.", "案件中出现新证据。"),
    ("emergency", "/ɪˈmɜːdʒənsi/", "n.", "紧急情况；突发事件", "In case of emergency, call 120.", "如有紧急情况，请拨打120。"),
    ("emission", "/ɪˈmɪʃn/", "n.", "排放；散发；发射", "The government aims to reduce carbon emissions.", "政府旨在减少碳排放。"),
    ("emotion", "/ɪˈməʊʃn/", "n.", "情感；感情；情绪", "The movie stirred strong emotions.", "这部电影引发了强烈的情感。"),
    ("emphasis", "/ˈemfəsɪs/", "n.", "强调；重点；重要性", "The school puts great emphasis on discipline.", "学校非常强调纪律。"),
    ("employ", "/ɪmˈplɔɪ/", "v.", "雇用；使用；利用", "The company employs over 5000 people.", "该公司雇用了5000多人。"),
    ("enable", "/ɪˈneɪbl/", "v.", "使能够；使可能；启用", "Technology enables us to connect globally.", "技术使我们能够全球连接。"),
    ("encounter", "/ɪnˈkaʊntər/", "v./n.", "遭遇；邂逅；遇到", "I encountered many difficulties during the project.", "我在项目中遇到了很多困难。"),
    ("encourage", "/ɪnˈkʌrɪdʒ/", "v.", "鼓励；激励；促进", "Teachers should encourage students to ask questions.", "老师应该鼓励学生提问。"),
    ("endure", "/ɪnˈdjʊər/", "v.", "忍受；忍耐；持久", "The pain was hard to endure.", "痛苦难以忍受。"),
    ("energetic", "/ˌenəˈdʒetɪk/", "adj.", "精力充沛的；充满活力的", "She is an energetic and enthusiastic person.", "她是一个精力充沛、充满热情的人。"),
    ("enforce", "/ɪnˈfɔːs/", "v.", "实施；执行；强制", "The police enforce the law.", "警察执行法律。"),
    ("engage", "/ɪnˈɡeɪdʒ/", "v.", "从事；吸引；聘用", "She engaged in various volunteer activities.", "她参加了各种志愿活动。"),
    ("enhance", "/ɪnˈhɑːns/", "v.", "提高；增强；增进", "Regular exercise enhances your health.", "经常锻炼能增进健康。"),
    ("enormous", "/ɪˈnɔːməs/", "adj.", "巨大的；庞大的", "The project requires an enormous amount of money.", "该项目需要巨额资金。"),
    ("ensure", "/ɪnˈʃʊər/", "v.", "确保；保证；担保", "Please ensure all doors are locked.", "请确保所有门都锁好了。"),
    ("enterprise", "/ˈentəpraɪz/", "n.", "企业；事业；进取心", "He started his own enterprise at age 25.", "他25岁时创办了自己的企业。"),
    ("entertain", "/ˌentəˈteɪn/", "v.", "娱乐；款待；抱有", "The magician entertained the children.", "魔术师逗乐了孩子们。"),
    ("enthusiasm", "/ɪnˈθjuːziazəm/", "n.", "热情；热忱；积极性", "The team showed great enthusiasm for the project.", "团队对该项目表现出极大的热情。"),
    ("entire", "/ɪnˈtaɪər/", "adj.", "全部的；整个的；完整的", "I spent the entire day studying.", "我花了一整天学习。"),
    ("entitle", "/ɪnˈtaɪtl/", "v.", "使有资格；给...命名", "You are entitled to a refund.", "你有权获得退款。"),
    ("environment", "/ɪnˈvaɪrənmənt/", "n.", "环境；周围状况", "We must protect the environment.", "我们必须保护环境。"),
    ("epidemic", "/ˌepɪˈdemɪk/", "n./adj.", "流行病；流行性的", "The epidemic spread rapidly.", "流行病迅速传播。"),
    ("episode", "/ˈepɪsəʊd/", "n.", "插曲；片段；一集", "This is my favorite episode of the series.", "这是这个系列中我最喜欢的一集。"),
    ("equivalent", "/ɪˈkwɪvələnt/", "adj./n.", "等价的；相等的；等值", "A dollar is equivalent to about seven yuan.", "一美元大约相当于七元人民币。"),
    ("erosion", "/ɪˈrəʊʒn/", "n.", "侵蚀；腐蚀；削弱", "Soil erosion is a serious problem.", "土壤侵蚀是一个严重问题。"),
    ("especially", "/ɪˈspeʃəli/", "adv.", "特别地；尤其；格外", "I love flowers, especially roses.", "我喜欢花，尤其是玫瑰。"),
    ("essential", "/ɪˈsenʃl/", "adj./n.", "必要的；本质的；要素", "Water is essential for life.", "水对生命是必不可少的。"),
    ("establish", "/ɪˈstæblɪʃ/", "v.", "建立；设立；确立", "The company was established in 2000.", "该公司成立于2000年。"),
    ("estimate", "/ˈestɪmeɪt/", "v./n.", "估计；估算；评价", "The cost is estimated at one million dollars.", "成本估计为一百万美元。"),
    ("evaluate", "/ɪˈvæljueɪt/", "v.", "评价；评估；估值", "We need to evaluate the effectiveness of the program.", "我们需要评估该计划的有效性。"),
    ("evident", "/ˈevɪdənt/", "adj.", "明显的；明白的", "It was evident that he was lying.", "很明显他在说谎。"),
    ("evolution", "/ˌiːvəˈluːʃn/", "n.", "进化；演变；发展", "Darwins theory of evolution changed biology.", "达尔文的进化论改变了生物学。"),
    ("exact", "/ɪɡˈzækt/", "adj./v.", "精确的；准确的；要求", "What is the exact time?", "确切时间是几点？"),
    ("exaggerate", "/ɪɡˈzædʒəreɪt/", "v.", "夸张；夸大；言过其实", "He tends to exaggerate his achievements.", "他倾向于夸大自己的成就。"),
    ("examine", "/ɪɡˈzæmɪn/", "v.", "检查；审查；考试", "The doctor examined the patient carefully.", "医生仔细检查了病人。"),
    ("exceed", "/ɪkˈsiːd/", "v.", "超过；超越；胜过", "Do not exceed the speed limit.", "不要超过速度限制。"),
    ("excellent", "/ˈeksələnt/", "adj.", "优秀的；卓越的；杰出的", "She is an excellent student.", "她是一名优秀的学生。"),
    ("exception", "/ɪkˈsepʃn/", "n.", "例外；除外", "Everyone must follow the rules, with no exceptions.", "每个人都必须遵守规则，没有例外。"),
    ("excess", "/ɪkˈses/", "n./adj.", "过量；过剩；额外的", "Eating to excess is harmful to health.", "吃得过量对健康有害。"),
    ("exchange", "/ɪksˈtʃeɪndʒ/", "v./n.", "交换；兑换；交流", "We exchanged ideas during the meeting.", "我们在会议期间交流了想法。"),
    ("exclude", "/ɪkˈskluːd/", "v.", "排除；排斥；拒绝", "The price excludes tax.", "价格不含税。"),
    ("execute", "/ˈeksɪkjuːt/", "v.", "执行；实施；处决", "The plan was executed perfectly.", "计划执行得很完美。"),
    ("exemplify", "/ɪɡˈzemplɪfaɪ/", "v.", "例证；举例说明", "This case exemplifies the challenges we face.", "这个案例例证了我们面临的挑战。"),
    ("exhaust", "/ɪɡˈzɔːst/", "v./n.", "耗尽；使筋疲力尽；排气", "The long journey exhausted everyone.", "长途旅行让每个人都精疲力尽。"),
    ("exhibit", "/ɪɡˈzɪbɪt/", "v./n.", "展出；展览；展示", "The museum exhibits works by local artists.", "博物馆展出当地艺术家的作品。"),
    ("expand", "/ɪkˈspænd/", "v.", "扩大；扩展；膨胀", "The company plans to expand into Asian markets.", "公司计划扩展到亚洲市场。"),
    ("expect", "/ɪkˈspekt/", "v.", "期望；预期；预料", "I expect you to arrive on time.", "我期望你准时到达。"),
    ("expense", "/ɪkˈspens/", "n.", "费用；花费；代价", "Living expenses are high in big cities.", "大城市的生活费用很高。"),
    ("experiment", "/ɪkˈsperɪmənt/", "n./v.", "实验；试验", "The scientist conducted a series of experiments.", "科学家进行了一系列实验。"),
    ("expert", "/ˈekspɜːt/", "n./adj.", "专家；内行；熟练的", "She is an expert in art history.", "她是艺术史专家。"),
    ("explain", "/ɪkˈspleɪn/", "v.", "解释；说明；阐明", "Can you explain the rules to me?", "你能给我解释一下规则吗？"),
    ("exploit", "/ɪkˈsplɔɪt/", "v./n.", "利用；开发；剥削", "We need to exploit new opportunities.", "我们需要利用新的机会。"),
    ("explore", "/ɪkˈsplɔːr/", "v.", "探索；探讨；考察", "We explored different options before deciding.", "我们在决定之前探讨了不同的选择。"),
    ("export", "/ˈekspɔːt/", "v./n.", "出口；输出；出口产品", "The country exports oil to many nations.", "该国向许多国家出口石油。"),
    ("expose", "/ɪkˈspəʊz/", "v.", "暴露；揭露；使接触", "The investigation exposed widespread corruption.", "调查揭露了广泛的腐败。"),
    ("extend", "/ɪkˈstend/", "v.", "扩展；延伸；延长", "We decided to extend our stay.", "我们决定延长停留时间。"),
    ("extensive", "/ɪkˈstensɪv/", "adj.", "广泛的；大量的；广阔的", "The storm caused extensive damage.", "暴风雨造成了广泛的破坏。"),
    ("extent", "/ɪkˈstent/", "n.", "程度；范围；限度", "To some extent, I agree with you.", "在某种程度上，我同意你的看法。"),
    ("external", "/ɪkˈstɜːnl/", "adj.", "外部的；外界的；对外的", "The company hired an external consultant.", "公司聘请了一位外部顾问。"),
    ("extraordinary", "/ɪkˈstrɔːdɪnəri/", "adj.", "非凡的；特别的；惊人的", "She has an extraordinary talent for music.", "她在音乐方面有非凡的天赋。"),
    ("extreme", "/ɪkˈstriːm/", "adj./n.", "极端的；极度的；极端", "The weather conditions were extreme.", "天气条件极其恶劣。"),
    ("facilitate", "/fəˈsɪlɪteɪt/", "v.", "促进；使便利", "The new software will facilitate the workflow.", "新软件将促进工作流程。"),
    ("faculty", "/ˈfæklti/", "n.", "才能；全体教员；系；科", "She is a member of the faculty.", "她是教员中的一员。"),
    ("fade", "/feɪd/", "v.", "褪色；逐渐消失；凋谢", "The colors will fade over time.", "颜色会随时间褪去。"),
    ("faith", "/feɪθ/", "n.", "信仰；信念；信任", "I have faith in your ability to succeed.", "我相信你有能力成功。"),
    ("fame", "/feɪm/", "n.", "名声；声誉；名气", "She achieved fame at a young age.", "她年轻时就成了名。"),
    ("fashion", "/ˈfæʃn/", "n./v.", "时尚；方式；形成", "Fashion trends change quickly.", "时尚潮流变化很快。"),
    ("fatal", "/ˈfeɪtl/", "adj.", "致命的；毁灭性的；重大的", "The accident was fatal.", "这起事故是致命的。"),
    ("fatigue", "/fəˈtiːɡ/", "n./v.", "疲劳；疲乏；使疲劳", "Physical and mental fatigue can affect performance.", "身心疲劳会影响表现。"),
    ("fault", "/fɔːlt/", "n./v.", "过错；缺点；故障", "Its my fault that we missed the train.", "我们错过火车是我的错。"),
    ("feasible", "/ˈfiːzəbl/", "adj.", "可行的；可能的；合理的", "We need to find a feasible solution.", "我们需要找到一个可行的解决方案。"),
    ("feature", "/ˈfiːtʃər/", "n./v.", "特征；特色；以...为特色", "The new phone has many advanced features.", "这款新手机有很多先进功能。"),
    ("federal", "/ˈfedərəl/", "adj.", "联邦的；联合的；同盟的", "The federal government passed a new law.", "联邦政府通过了一项新法律。"),
    ("feedback", "/ˈfiːdbæk/", "n.", "反馈；反馈意见", "We value your feedback on our service.", "我们重视您对我们服务的反馈。"),
    ("fertile", "/ˈfɜːtaɪl/", "adj.", "肥沃的；富饶的；能生育的", "The soil in this region is very fertile.", "这个地区的土壤非常肥沃。"),
    ("fiction", "/ˈfɪkʃn/", "n.", "小说；虚构；编造", "She enjoys reading science fiction.", "她喜欢读科幻小说。"),
    ("fierce", "/fɪəs/", "adj.", "凶猛的；激烈的；强烈的", "The competition is fierce.", "竞争很激烈。"),
    ("figure", "/ˈfɪɡər/", "n./v.", "数字；人物；图形；认为", "Can you figure out the answer?", "你能想出答案吗？"),
    ("finance", "/ˈfaɪnæns/", "n./v.", "财务；金融；资助", "He works in the finance department.", "他在财务部工作。"),
    ("flexible", "/ˈfleksəbl/", "adj.", "灵活的；柔韧的；可变通的", "We need a flexible schedule.", "我们需要灵活的时间安排。"),
    ("flourish", "/ˈflʌrɪʃ/", "v.", "繁荣；茂盛；兴旺", "The business flourished during the 1990s.", "这家企业在20世纪90年代蓬勃发展。"),
    ("fluctuate", "/ˈflʌktʃueɪt/", "v.", "波动；起伏；变动", "Stock prices fluctuate daily.", "股票价格每天波动。"),
    ("forecast", "/ˈfɔːkɑːst/", "v./n.", "预测；预报；展望", "The weather forecast says it will rain.", "天气预报说会下雨。"),
    ("foreign", "/ˈfɒrən/", "adj.", "外国的；外来的；陌生的", "She can speak several foreign languages.", "她会说几门外语。"),
    ("formula", "/ˈfɔːmjələ/", "n.", "公式；配方；准则", "There is no magic formula for success.", "成功没有神奇的公式。"),
    ("forthcoming", "/ˌfɔːθˈkʌmɪŋ/", "adj.", "即将到来的；乐于提供的", "More details will be forthcoming.", "更多细节即将公布。"),
    ("fortune", "/ˈfɔːtʃuːn/", "n.", "财富；运气；命运", "He made a fortune in real estate.", "他通过房地产发了财。"),
    ("foundation", "/faʊnˈdeɪʃn/", "n.", "基础；地基；基金会", "The course provides a solid foundation in mathematics.", "这门课程为数学打下坚实基础。"),
    ("fraction", "/ˈfrækʃn/", "n.", "分数；小部分；片段", "Only a fraction of the population voted.", "只有一小部分人口投票。"),
    ("fragment", "/ˈfræɡmənt/", "n./v.", "碎片；片段；使破碎", "The glass shattered into fragments.", "玻璃碎成了碎片。"),
    ("framework", "/ˈfreɪmwɜːk/", "n.", "框架；结构；体系", "The report provides a framework for discussion.", "报告提供了讨论的框架。"),
    ("frequency", "/ˈfriːkwənsi/", "n.", "频率；频繁；发生次数", "The frequency of earthquakes has increased.", "地震的频率增加了。"),
    ("friction", "/ˈfrɪkʃn/", "n.", "摩擦；冲突；不和", "There is some friction between the two departments.", "两个部门之间有些摩擦。"),
    ("fulfill", "/fʊlˈfɪl/", "v.", "履行；实现；满足", "She fulfilled her dream of becoming a doctor.", "她实现了当医生的梦想。"),
    ("function", "/ˈfʌŋkʃn/", "n./v.", "功能；作用；运转", "The machine is not functioning properly.", "机器运行不正常。"),
    ("fundamental", "/ˌfʌndəˈmentl/", "adj./n.", "基本的；根本的；基础", "There are fundamental differences between the two systems.", "这两个系统有根本的区别。"),
    ("furthermore", "/ˌfɜːðəˈmɔːr/", "adv.", "此外；而且；再者", "The house is beautiful; furthermore, the price is reasonable.", "房子很漂亮，而且价格合理。"),
    ("generate", "/ˈdʒenəreɪt/", "v.", "产生；生成；发电", "The wind turbines generate electricity.", "风力涡轮机发电。"),
    ("generous", "/ˈdʒenərəs/", "adj.", "慷慨的；大方的；宽厚的", "She made a generous donation to charity.", "她向慈善机构慷慨捐款。"),
    ("genetic", "/dʒəˈnetɪk/", "adj.", "遗传的；基因的；起源的", "Genetic factors play a role in many diseases.", "遗传因素在许多疾病中起作用。"),
    ("genius", "/ˈdʒiːniəs/", "n.", "天才；天赋；才华", "Einstein was a mathematical genius.", "爱因斯坦是一位数学天才。"),
    ("genuine", "/ˈdʒenjuɪn/", "adj.", "真正的；真诚的；真实的", "She showed genuine concern for others.", "她对他人表现出真诚的关心。"),
    ("gesture", "/ˈdʒestʃər/", "n./v.", "手势；姿势；表示", "He made a gesture of apology.", "他做出了道歉的手势。"),
    ("global", "/ˈɡləʊbl/", "adj.", "全球的；全世界的；全面的", "Climate change is a global issue.", "气候变化是一个全球性问题。"),
    ("glorious", "/ˈɡlɔːriəs/", "adj.", "光荣的；辉煌的；壮丽的", "The team achieved a glorious victory.", "该队取得了辉煌的胜利。"),
    ("govern", "/ˈɡʌvn/", "v.", "统治；治理；支配", "The country is governed by law.", "这个国家依法治理。"),
    ("grace", "/ɡreɪs/", "n./v.", "优雅；恩惠；宽限", "She danced with grace.", "她舞姿优雅。"),
    ("gradual", "/ˈɡrædʒuəl/", "adj.", "逐渐的；渐进的", "There has been a gradual improvement in her health.", "她的健康状况逐渐好转。"),
    ("grant", "/ɡrɑːnt/", "v./n.", "授予；准予；拨款", "The university granted her a scholarship.", "大学授予她奖学金。"),
    ("grasp", "/ɡrɑːsp/", "v./n.", "抓住；理解；掌握", "She grasped the concept quickly.", "她很快就掌握了这个概念。"),
    ("gratitude", "/ˈɡrætɪtjuːd/", "n.", "感激；感谢；感恩", "I express my gratitude for your help.", "我感谢你的帮助。"),
    ("gravity", "/ˈɡrævəti/", "n.", "重力；严肃；严重性", "He didnt understand the gravity of the situation.", "他不理解情况的严重性。"),
    ("guarantee", "/ˌɡærənˈtiː/", "v./n.", "保证；担保；保修", "The product comes with a one-year guarantee.", "本产品提供一年保修。"),
    ("guideline", "/ˈɡaɪdlaɪn/", "n.", "指导方针；指南；准则", "Follow the safety guidelines carefully.", "仔细遵守安全指南。"),
    ("guilty", "/ˈɡɪlti/", "adj.", "有罪的；内疚的；有过失的", "The jury found him guilty.", "陪审团认定他有罪。"),
    ("handle", "/ˈhændl/", "v./n.", "处理；操作；手柄", "She knows how to handle difficult customers.", "她知道如何应对难缠的客户。"),
    ("hardship", "/ˈhɑːdʃɪp/", "n.", "艰难；困苦；苦难", "They endured great hardship during the war.", "他们在战争期间忍受了巨大的苦难。"),
    ("harmony", "/ˈhɑːməni/", "n.", "和谐；协调；融洽", "We live in harmony with nature.", "我们与自然和谐相处。"),
    ("harness", "/ˈhɑːnɪs/", "v./n.", "利用；驾驭；马具", "We need to harness renewable energy.", "我们需要利用可再生能源。"),
    ("harsh", "/hɑːʃ/", "adj.", "严厉的；严酷的；刺耳的", "The punishment was too harsh.", "惩罚太严厉了。"),
    ("hazard", "/ˈhæzəd/", "n./v.", "危险；危害；冒险", "Smoking is a health hazard.", "吸烟对健康有害。"),
    ("hesitate", "/ˈhezɪteɪt/", "v.", "犹豫；迟疑；不情愿", "Dont hesitate to ask if you need help.", "如果你需要帮助，不要犹豫。"),
    ("highlight", "/ˈhaɪlaɪt/", "v./n.", "强调；突出；精彩部分", "The report highlights the key issues.", "报告强调了关键问题。"),
    ("horizon", "/həˈraɪzn/", "n.", "地平线；眼界；范围", "Travel broadens your horizons.", "旅行开阔眼界。"),
    ("hostile", "/ˈhɒstaɪl/", "adj.", "敌对的；不友好的；不利的", "The audience gave a hostile reaction.", "观众做出了敌对的反应。"),
    ("humanity", "/hjuːˈmænəti/", "n.", "人类；人性；人道", "The disaster was a tragedy for all humanity.", "这场灾难是全人类的悲剧。"),
    ("identify", "/aɪˈdentɪfaɪ/", "v.", "识别；确认；鉴定", "Can you identify the suspect?", "你能辨认出嫌疑人吗？"),
    ("ignorance", "/ˈɪɡnərəns/", "n.", "无知；愚昧；不了解", "Ignorance of the law is no excuse.", "不懂法不是借口。"),
    ("illustrate", "/ˈɪləstreɪt/", "v.", "说明；阐明；给...加插图", "The diagram illustrates how the system works.", "图表说明了系统如何工作。"),
    ("image", "/ˈɪmɪdʒ/", "n.", "图像；形象；印象", "The company wants to improve its public image.", "公司想要改善其公众形象。"),
    ("imagine", "/ɪˈmædʒɪn/", "v.", "想象；设想；猜测", "Imagine living in a world without internet.", "想象一下生活在没有互联网的世界。"),
    ("imitate", "/ˈɪmɪteɪt/", "v.", "模仿；仿效；仿制", "Children often imitate their parents.", "孩子常常模仿父母。"),
    ("immediate", "/ɪˈmiːdiət/", "adj.", "立即的；直接的；紧迫的", "Please take immediate action.", "请立即采取行动。"),
    ("immense", "/ɪˈmens/", "adj.", "巨大的；极大的；无边无际的", "The project required an immense amount of effort.", "该项目需要巨大的努力。"),
    ("immigrant", "/ˈɪmɪɡrənt/", "n./adj.", "移民；侨民", "The city has a large immigrant population.", "该市有大量移民人口。"),
    ("immune", "/ɪˈmjuːn/", "adj.", "免疫的；不受影响的；豁免的", "Regular exercise boosts your immune system.", "经常锻炼能增强免疫系统。"),
    ("impact", "/ˈɪmpækt/", "n./v.", "影响；冲击；撞击", "The new policy will have a significant impact.", "新政策将产生重大影响。"),
    ("implement", "/ˈɪmplɪment/", "v./n.", "实施；执行；工具", "The government implemented the reform.", "政府实施了改革。"),
    ("implication", "/ˌɪmplɪˈkeɪʃn/", "n.", "含义；暗示；影响", "What are the implications of this decision?", "这个决定有什么影响？"),
    ("imply", "/ɪmˈplaɪ/", "v.", "暗示；意味着；隐含", "What are you implying by that statement?", "你那句话暗示什么？"),
    ("import", "/ˈɪmpɔːt/", "v./n.", "进口；输入；重要性", "The country imports most of its oil.", "该国进口大部分石油。"),
    ("impose", "/ɪmˈpəʊz/", "v.", "强加；征收（税款）；推行", "The government imposed a new tax on luxury goods.", "政府对奢侈品征收了新税。"),
    ("impress", "/ɪmˈpres/", "v.", "给...深刻印象；使钦佩", "She impressed everyone with her intelligence.", "她的智慧给每个人留下了深刻印象。"),
    ("improve", "/ɪmˈpruːv/", "v.", "改善；提高；改进", "Regular practice will improve your skills.", "定期练习会提高你的技能。"),
    ("impulse", "/ˈɪmpʌls/", "n.", "冲动；推动；脉冲", "She bought the dress on impulse.", "她一时冲动买了这条裙子。"),
    ("incentive", "/ɪnˈsentɪv/", "n.", "激励；刺激；诱因", "The company offers bonuses as an incentive.", "公司提供奖金作为激励。"),
    ("incident", "/ˈɪnsɪdənt/", "n.", "事件；事变；插曲", "The incident was reported to the police.", "该事件已向警方报告。"),
    ("incline", "/ɪnˈklaɪn/", "v./n.", "倾斜；倾向；斜坡", "I incline to the view that we should wait.", "我倾向于我们应该等待的观点。"),
    ("include", "/ɪnˈkluːd/", "v.", "包括；包含；计入", "The price includes breakfast.", "价格包括早餐。"),
    ("income", "/ˈɪnkʌm/", "n.", "收入；收益；所得", "His annual income exceeds $100,000.", "他的年收入超过10万美元。"),
    ("incorporate", "/ɪnˈkɔːpəreɪt/", "v.", "合并；包含；组成公司", "The company was incorporated in 2010.", "该公司成立于2010年。"),
    ("increase", "/ɪnˈkriːs/", "v./n.", "增加；增长；提高", "Sales increased by 20% this quarter.", "本季度销售额增长了20%。"),
    ("incredible", "/ɪnˈkredəbl/", "adj.", "难以置信的；极好的；惊人的", "The view from the top was incredible.", "从山顶看到的景色令人难以置信。"),
    ("independent", "/ˌɪndɪˈpendənt/", "adj.", "独立的；自主的；无党派", "She is very independent for her age.", "以她的年龄来说，她非常独立。"),
    ("indicate", "/ˈɪndɪkeɪt/", "v.", "表明；指示；暗示", "The evidence indicates that he is guilty.", "证据表明他有罪。"),
    ("individual", "/ˌɪndɪˈvɪdʒuəl/", "adj./n.", "个人的；单独的；个体", "Each individual has their own strengths.", "每个人都有自己的优势。"),
    ("induce", "/ɪnˈdjuːs/", "v.", "诱导；引起；劝使", "The drug can induce sleep.", "这种药可以诱导睡眠。"),
    ("inevitable", "/ɪnˈevɪtəbl/", "adj.", "不可避免的；必然的", "Change is inevitable in life.", "生活中的变化是不可避免的。"),
    ("infect", "/ɪnˈfekt/", "v.", "感染；传染；影响", "The virus infected thousands of people.", "这种病毒感染了成千上万的人。"),
    ("infer", "/ɪnˈfɜːr/", "v.", "推断；推论；暗示", "What can we infer from the data?", "我们能从数据中推断出什么？"),
    ("infinite", "/ˈɪnfɪnət/", "adj.", "无限的；无穷的；极大的", "The universe is infinite.", "宇宙是无限的。"),
    ("influence", "/ˈɪnfluəns/", "n./v.", "影响；势力；感化", "Her words had a great influence on me.", "她的话对我影响很大。"),
]
