# High-frequency words A-B
HIGH_WORDS = [
    ("abandon", "/əˈbændən/", "v.", "放弃；抛弃", "They had to abandon the plan due to lack of funding.", "由于缺乏资金，他们不得不放弃这个计划。"),
    ("ability", "/əˈbɪləti/", "n.", "能力；才能", "She has the ability to solve complex problems quickly.", "她有能力快速解决复杂问题。"),
    ("abroad", "/əˈbrɔːd/", "adv.", "在国外；到国外", "He dreams of studying abroad next year.", "他梦想着明年出国留学。"),
    ("absence", "/ˈæbsəns/", "n.", "缺席；不在", "His absence from the meeting was noted by everyone.", "他的缺席引起了每个人的注意。"),
    ("absolute", "/ˈæbsəluːt/", "adj.", "绝对的；完全的", "You have my absolute trust and support.", "你得到我绝对的信任和支持。"),
    ("absorb", "/əbˈzɔːb/", "v.", "吸收；吸引", "Plants absorb carbon dioxide and release oxygen.", "植物吸收二氧化碳并释放氧气。"),
    ("abstract", "/ˈæbstrækt/", "adj.", "抽象的；摘要", "The concept is too abstract for most people.", "这个概念对大多数人来说太抽象了。"),
    ("abundant", "/əˈbʌndənt/", "adj.", "丰富的；充裕的", "The region has abundant natural resources.", "这个地区有丰富的自然资源。"),
    ("abuse", "/əˈbjuːs/", "n./v.", "滥用；虐待", "The system is open to abuse by dishonest people.", "这个系统容易被不诚实的人滥用。"),
    ("academic", "/ˌækəˈdemɪk/", "adj.", "学术的；学院的", "She has published several academic papers.", "她发表了多篇学术论文。"),
    ("accelerate", "/əkˈseləreɪt/", "v.", "加速；促进", "The government plans to accelerate economic growth.", "政府计划加速经济增长。"),
    ("access", "/ˈækses/", "n./v.", "进入；通道；访问", "Students have free access to the online library.", "学生可以免费访问在线图书馆。"),
    ("accommodate", "/əˈkɒmədeɪt/", "v.", "容纳；提供住宿；适应", "The hotel can accommodate up to 500 guests.", "这家酒店最多可容纳500位客人。"),
    ("accompany", "/əˈkʌmpəni/", "v.", "陪伴；伴随", "I will accompany you to the airport tomorrow.", "我明天会陪你去机场。"),
    ("accomplish", "/əˈkʌmplɪʃ/", "v.", "完成；实现", "He accomplished his goal of running a marathon.", "他完成了跑马拉松的目标。"),
    ("account", "/əˈkaʊnt/", "n./v.", "账户；说明；占比", "You need to create an account to use this service.", "你需要创建一个账户才能使用这项服务。"),
    ("accumulate", "/əˈkjuːmjəleɪt/", "v.", "积累；积聚", "Over the years, he accumulated a vast collection of books.", "多年来，他积累了大量藏书。"),
    ("accurate", "/ˈækjərət/", "adj.", "准确的；精确的", "The data must be accurate for the experiment.", "数据必须准确才能让实验成功。"),
    ("achieve", "/əˈtʃiːv/", "v.", "实现；达到", "She worked hard to achieve her dreams.", "她努力工作以实现自己的梦想。"),
    ("acknowledge", "/əkˈnɒlɪdʒ/", "v.", "承认；感谢", "He acknowledged his mistake and apologized.", "他承认了自己的错误并道歉。"),
    ("acquire", "/əˈkwaɪər/", "v.", "获得；习得", "It takes years to acquire a new language fluently.", "流利掌握一门新语言需要多年时间。"),
    ("adapt", "/əˈdæpt/", "v.", "适应；改编", "Animals must adapt to their environment to survive.", "动物必须适应环境才能生存。"),
    ("adequate", "/ˈædɪkwət/", "adj.", "足够的；适当的", "We need adequate time to prepare for the exam.", "我们需要足够的时间来准备考试。"),
    ("adjust", "/əˈdʒʌst/", "v.", "调整；适应", "You need to adjust your study habits.", "你需要调整你的学习习惯。"),
    ("administration", "/ədˌmɪnɪˈstreɪʃn/", "n.", "管理；行政", "The administration has implemented new policies.", "管理部门实施了新政策。"),
    ("adopt", "/əˈdɒpt/", "v.", "采用；收养", "The company decided to adopt a new strategy.", "公司决定采用新策略。"),
    ("advance", "/ədˈvɑːns/", "v./n.", "前进；进步；预付", "Technology has advanced rapidly in recent years.", "近年来技术进步迅速。"),
    ("advantage", "/ədˈvɑːntɪdʒ/", "n.", "优势；有利条件", "Being bilingual gives you a major advantage.", "掌握双语给你带来巨大优势。"),
    ("adverse", "/ədˈvɜːs/", "adj.", "不利的；相反的", "The drug may cause adverse side effects.", "这种药物可能引起不良副作用。"),
    ("advocate", "/ˈædvəkeɪt/", "v./n.", "提倡；拥护；律师", "Many experts advocate for renewable energy.", "许多专家提倡使用可再生能源。"),
    ("affect", "/əˈfekt/", "v.", "影响；感动", "The climate change affects everyone globally.", "气候变化影响着全球每个人。"),
    ("afford", "/əˈfɔːd/", "v.", "负担得起；提供", "I can't afford to waste any more time.", "我不能再浪费时间了。"),
    ("agenda", "/əˈdʒendə/", "n.", "议程；议事日程", "The first item on the agenda is budget review.", "议程上的第一项是预算审查。"),
    ("aggressive", "/əˈɡresɪv/", "adj.", "侵略的；好斗的；积极的", "The company adopted an aggressive marketing strategy.", "公司采取了积极的营销策略。"),
    ("allocate", "/ˈæləkeɪt/", "v.", "分配；拨出", "The government allocated funds for education.", "政府拨出资金用于教育。"),
    ("alternative", "/ɔːlˈtɜːnətɪv/", "adj./n.", "替代的；选择", "We need to find an alternative solution.", "我们需要找到替代方案。"),
    ("amaze", "/əˈmeɪz/", "v.", "使惊奇；使惊愕", "The magician's performance amazed the audience.", "魔术师的表演令观众惊叹。"),
    ("ambition", "/æmˈbɪʃn/", "n.", "雄心；野心", "Her ambition is to become a successful entrepreneur.", "她的雄心是成为一名成功的企业家。"),
    ("analyze", "/ˈænəlaɪz/", "v.", "分析；解析", "We need to analyze the data carefully.", "我们需要仔细分析数据。"),
    ("annual", "/ˈænjuəl/", "adj.", "每年的；年度的", "The company holds an annual meeting every December.", "公司每年十二月举行年会。"),
]

HIGH_WORDS.extend([
    ("anticipate", "/ænˈtɪsɪpeɪt/", "v.", "预期；期望；预料", "We anticipate strong demand for the new product.", "我们预期新产品会有强劲需求。"),
    ("anxiety", "/æŋˈzaɪəti/", "n.", "焦虑；忧虑", "Exam anxiety is common among students.", "考试焦虑在学生中很常见。"),
    ("apparent", "/əˈpærənt/", "adj.", "明显的；表面上的", "It became apparent that he was lying.", "很明显他在说谎。"),
    ("appeal", "/əˈpiːl/", "v./n.", "呼吁；上诉；吸引", "The charity appealed for donations.", "慈善机构呼吁捐款。"),
    ("appetite", "/ˈæpɪtaɪt/", "n.", "胃口；欲望", "Exercise can help improve your appetite.", "运动有助于改善食欲。"),
    ("applaud", "/əˈplɔːd/", "v.", "鼓掌；称赞", "The audience applauded the performers.", "观众为表演者鼓掌。"),
    ("applicable", "/əˈplɪkəbl/", "adj.", "适用的；合适的", "These rules are not applicable to this case.", "这些规则不适用于此案。"),
    ("apply", "/əˈplaɪ/", "v.", "申请；应用；适用", "You should apply for the scholarship early.", "你应该尽早申请奖学金。"),
    ("appoint", "/əˈpɔɪnt/", "v.", "任命；指定", "The board appointed a new CEO.", "董事会任命了一位新CEO。"),
    ("appreciate", "/əˈpriːʃieɪt/", "v.", "欣赏；感激；增值", "I really appreciate your help.", "我非常感激你的帮助。"),
    ("approach", "/əˈprəʊtʃ/", "v./n.", "接近；方法；途径", "We need a new approach to solving this problem.", "我们需要一种新方法来解决这个问题。"),
    ("appropriate", "/əˈprəʊpriət/", "adj.", "适当的；恰当的", "Please wear appropriate clothing for the interview.", "请穿适合面试的服装。"),
    ("approve", "/əˈpruːv/", "v.", "批准；赞同", "The committee approved the proposal.", "委员会批准了该提案。"),
    ("approximate", "/əˈprɒksɪmət/", "adj.", "大约的；近似的", "The approximate cost is $500.", "大约费用是500美元。"),
    ("arise", "/əˈraɪz/", "v.", "出现；产生；起因于", "A new problem has arisen.", "出现了一个新问题。"),
    ("arrange", "/əˈreɪndʒ/", "v.", "安排；整理", "I will arrange a meeting for next week.", "我将安排下周的会议。"),
    ("artificial", "/ˌɑːtɪˈfɪʃl/", "adj.", "人工的；造作的", "Artificial intelligence is transforming our lives.", "人工智能正在改变我们的生活。"),
    ("assemble", "/əˈsembl/", "v.", "集合；组装", "The students assembled in the auditorium.", "学生们在礼堂集合。"),
    ("assess", "/əˈses/", "v.", "评估；评定", "It's difficult to assess the damage.", "很难评估损失程度。"),
    ("assign", "/əˈsaɪn/", "v.", "分配；指派", "The teacher assigned homework for the weekend.", "老师布置了周末作业。"),
    ("assist", "/əˈsɪst/", "v.", "援助；帮助", "Can you assist me with this task?", "你能帮我完成这个任务吗？"),
    ("associate", "/əˈsəʊsieɪt/", "v./n.", "联系；关联；同事", "We associate China with the Great Wall.", "我们提到中国就会联想到长城。"),
    ("assume", "/əˈsjuːm/", "v.", "假设；承担；呈现", "I assume you have read the instructions.", "我假设你已经阅读了说明。"),
    ("assure", "/əˈʃʊər/", "v.", "保证；向…保证", "I assure you that everything will be fine.", "我向你保证一切都会好的。"),
    ("atmosphere", "/ˈætməsfɪər/", "n.", "大气；氛围；环境", "The restaurant has a romantic atmosphere.", "这家餐厅有浪漫的氛围。"),
    ("attach", "/əˈtætʃ/", "v.", "附上；贴上；使附属", "Please attach your resume to the email.", "请将简历附在邮件中。"),
    ("attempt", "/əˈtempt/", "v./n.", "尝试；企图", "She attempted to solve the puzzle.", "她试图解开这个谜题。"),
    ("attend", "/əˈtend/", "v.", "参加；出席；照顾", "All students must attend the lecture.", "所有学生必须参加讲座。"),
    ("attitude", "/ˈætɪtjuːd/", "n.", "态度；看法", "A positive attitude is key to success.", "积极的态度是成功的关键。"),
    ("attract", "/əˈtrækt/", "v.", "吸引；引起", "The museum attracts many visitors each year.", "这个博物馆每年吸引许多游客。"),
    ("attribute", "/əˈtrɪbjuːt/", "v./n.", "归因于；属性", "She attributes her success to hard work.", "她把成功归因于努力工作。"),
    ("authority", "/ɔːˈθɒrəti/", "n.", "权威；当局；权力", "The local authorities are investigating the incident.", "地方当局正在调查此事。"),
    ("automatic", "/ˌɔːtəˈmætɪk/", "adj.", "自动的；无意识的", "The doors open automatically.", "门会自动打开。"),
    ("available", "/əˈveɪləbl/", "adj.", "可用的；有效的；可获得的", "Tickets are available online.", "门票可以在线购买。"),
    ("avenue", "/ˈævənjuː/", "n.", "林荫道；途径；方法", "We explored every avenue to solve the issue.", "我们探索了解决这个问题的所有途径。"),
    ("aware", "/əˈweər/", "adj.", "意识到的；知道的", "Are you aware of the risks involved?", "你意识到其中的风险了吗？"),
    ("balance", "/ˈbæləns/", "n./v.", "平衡；余额；权衡", "You need to balance work and life.", "你需要平衡工作和生活。"),
    ("barrier", "/ˈbæriər/", "n.", "障碍；屏障", "Language can be a barrier to communication.", "语言可能成为沟通的障碍。"),
    ("behalf", "/bɪˈhɑːf/", "n.", "代表；利益", "I am writing on behalf of my company.", "我代表我的公司写信。"),
    ("behave", "/bɪˈheɪv/", "v.", "行为；表现；运转", "Children should behave well in public.", "孩子在公共场合应该表现良好。"),
    ("belief", "/bɪˈliːf/", "n.", "相信；信念；信仰", "It is my belief that honesty is the best policy.", "我相信诚实是最好的策略。"),
    ("benefit", "/ˈbenɪfɪt/", "n./v.", "利益；好处；受益", "Regular exercise has many health benefits.", "经常锻炼对健康有很多好处。"),
    ("betray", "/bɪˈtreɪ/", "v.", "背叛；泄露", "He felt betrayed by his closest friend.", "他感到被最亲密的朋友背叛了。"),
    ("bewilder", "/bɪˈwɪldər/", "v.", "使迷惑；使不知所措", "The complex instructions bewildered the students.", "复杂的说明让学生们感到困惑。"),
    ("bias", "/ˈbaɪəs/", "n./v.", "偏见；偏向", "The article showed a clear bias.", "这篇文章显示出明显的偏见。"),
    ("bind", "/baɪnd/", "v.", "捆绑；约束；结合", "The contract binds both parties.", "合同对双方都有约束力。"),
    ("blame", "/bleɪm/", "v./n.", "责备；归咎于", "Don't blame others for your mistakes.", "不要把自己的错误归咎于别人。"),
    ("boost", "/buːst/", "v./n.", "促进；增加；提高", "The new policy will boost the economy.", "新政策将促进经济发展。"),
    ("boundary", "/ˈbaʊndri/", "n.", "边界；界限", "The river forms the boundary between the two countries.", "这条河构成了两国的边界。"),
    ("breakthrough", "/ˈbreɪkθruː/", "n.", "突破；重大发现", "Scientists made a major breakthrough in cancer research.", "科学家在癌症研究方面取得了重大突破。"),
])
