# Mid-frequency words A-F
MID_WORDS_A = [
    ("abnormal", "/æbˈnɔːml/", "adj.", "反常的；异常的", "Abnormal weather patterns have become more common.", "异常天气模式变得更加常见。"),
    ("abolish", "/əˈbɒlɪʃ/", "v.", "废除；废止；取消", "The government abolished the outdated law.", "政府废除了过时的法律。"),
    ("abrupt", "/əˈbrʌpt/", "adj.", "突然的；唐突的；陡峭的", "The meeting came to an abrupt end.", "会议突然结束了。"),
    ("absurd", "/əbˈsɜːd/", "adj.", "荒谬的；可笑的", "The idea seemed completely absurd.", "这个想法似乎完全荒谬。"),
    ("abundance", "/əˈbʌndəns/", "n.", "丰富；充裕；大量", "The area has an abundance of wildlife.", "该地区有丰富的野生动物。"),
    ("abuse", "/əˈbjuːs/", "n./v.", "滥用；虐待；辱骂", "Drug abuse can ruin your health.", "药物滥用会毁掉你的健康。"),
    ("academy", "/əˈkædəmi/", "n.", "学院；研究院；学会", "She studied at the Royal Academy of Music.", "她在皇家音乐学院学习。"),
    ("accelerate", "/əkˈseləreɪt/", "v.", "加速；促进", "Economic growth has accelerated this year.", "今年经济增长加速了。"),
    ("accessory", "/əkˈsesəri/", "n.", "附件；配件；同谋", "The store sells car accessories.", "这家店卖汽车配件。"),
    ("accommodation", "/əˌkɒməˈdeɪʃn/", "n.", "住宿；膳宿；调节", "The university provides accommodation for students.", "大学为学生提供住宿。"),
    ("accountant", "/əˈkaʊntənt/", "n.", "会计；会计师", "She works as a certified accountant.", "她是一名注册会计师。"),
    ("accumulation", "/əˌkjuːmjəˈleɪʃn/", "n.", "积累；积聚；堆积", "The accumulation of wealth takes time.", "财富的积累需要时间。"),
    ("accuse", "/əˈkjuːz/", "v.", "指控；指责；控告", "He was accused of stealing.", "他被指控偷窃。"),
    ("acid", "/ˈæsɪd/", "n./adj.", "酸；酸性的；尖刻的", "Lemon juice contains acid.", "柠檬汁含有酸。"),
    ("acquaintance", "/əˈkweɪntəns/", "n.", "熟人；认识；了解", "He is just a casual acquaintance.", "他只是个普通熟人。"),
    ("acquisition", "/ˌækwɪˈzɪʃn/", "n.", "获得；收购；习得", "The company made a major acquisition.", "该公司进行了一次重大收购。"),
    ("activate", "/ˈæktɪveɪt/", "v.", "激活；启动；使活动", "Press this button to activate the alarm.", "按这个按钮激活闹钟。"),
    ("acute", "/əˈkjuːt/", "adj.", "急性的；敏锐的；剧烈的", "She has acute hearing.", "她听觉敏锐。"),
    ("adaptation", "/ˌædæpˈteɪʃn/", "n.", "适应；改编；改编的作品", "The movie is an adaptation of the novel.", "这部电影改编自小说。"),
    ("addict", "/ˈædɪkt/", "n./v.", "上瘾者；使上瘾", "He is a drug addict.", "他是个吸毒成瘾者。"),
    ("adhere", "/ədˈhɪər/", "v.", "粘附；坚持；遵守", "You must adhere to the rules.", "你必须遵守规则。"),
    ("adjacent", "/əˈdʒeɪsnt/", "adj.", "邻近的；毗连的", "The hotel is adjacent to the station.", "酒店紧邻车站。"),
    ("administer", "/ədˈmɪnɪstər/", "v.", "管理；执行；给予", "The nurse administered first aid.", "护士进行了急救。"),
    ("adolescent", "/ˌædəˈlesnt/", "n./adj.", "青少年；青春期的", "Adolescent behavior can be unpredictable.", "青少年的行为可能难以预测。"),
    ("advent", "/ˈædvent/", "n.", "出现；到来； Advent（基督降临节）", "With the advent of the internet, communication changed.", "随着互联网的出现，沟通方式改变了。"),
    ("adverse", "/ədˈvɜːs/", "adj.", "不利的；相反的；敌对的", "The drug has adverse side effects.", "这种药物有不良副作用。"),
    ("aerial", "/ˈeəriəl/", "adj./n.", "空中的；航空的；天线", "The aerial view of the city is stunning.", "这座城市的空中景色令人惊叹。"),
    ("aesthetic", "/iːsˈθetɪk/", "adj.", "美学的；审美的；艺术的", "The building has great aesthetic value.", "这座建筑具有很高的美学价值。"),
    ("affection", "/əˈfekʃn/", "n.", "喜爱；感情；爱慕", "She showed great affection for her children.", "她对孩子们表现出深厚的爱。"),
    ("affiliate", "/əˈfɪlieɪt/", "v./n.", "使附属；加入；分支机构", "The college is affiliated with the university.", "这所学院附属于该大学。"),
    ("aggregate", "/ˈæɡrɪɡət/", "v./n./adj.", "总计；集合；合计的", "The aggregate of all sales reached $1 million.", "总销售额达到一百万美元。"),
    ("aggression", "/əˈɡreʃn/", "n.", "侵略；攻击；侵犯", "The aggression must be stopped.", "必须停止侵略。"),
    ("agitate", "/ˈædʒɪteɪt/", "v.", "鼓动；煽动；使焦虑", "The workers agitated for better conditions.", "工人们鼓动争取更好的条件。"),
    ("agony", "/ˈæɡəni/", "n.", "极度痛苦；苦恼", "She was in agony after the accident.", "事故后她处于极度痛苦中。"),
    ("agreeable", "/əˈɡriːəbl/", "adj.", "令人愉快的；同意的；适合的", "The weather is very agreeable today.", "今天天气非常宜人。"),
    ("ailment", "/ˈeɪlmənt/", "n.", "小病；不适；疾病", "The doctor treated minor ailments.", "医生治疗了小病。"),
    ("albeit", "/ɔːlˈbiːɪt/", "conj.", "虽然；尽管", "It was a difficult task, albeit rewarding.", "虽然任务艰巨，但很有收获。"),
    ("alien", "/ˈeɪliən/", "adj./n.", "外国的；陌生的；外星人", "The customs seemed alien to me.", "这些习俗对我来说很陌生。"),
    ("alienate", "/ˈeɪliəneɪt/", "v.", "使疏远；使不友好；转让", "His behavior alienated his friends.", "他的行为使朋友们疏远了他。"),
    ("alignment", "/əˈlaɪnmənt/", "n.", "对齐；结盟；排列", "The wheels need alignment.", "车轮需要校准。"),
    ("allege", "/əˈledʒ/", "v.", "断言；声称；指控", "The police allege that he stole the car.", "警方声称他偷了车。"),
    ("alleviate", "/əˈliːvieɪt/", "v.", "减轻；缓解；缓和", "The medicine helped alleviate the pain.", "药物帮助缓解了疼痛。"),
    ("alliance", "/əˈlaɪəns/", "n.", "联盟；同盟；联合", "The two countries formed an alliance.", "两国结成了联盟。"),
    ("allocate", "/ˈæləkeɪt/", "v.", "分配；拨出；划拨", "The funds were allocated to education.", "资金被拨给了教育部门。"),
    ("allot", "/əˈlɒt/", "v.", "分配；拨给；分派", "Each student was allotted a seat.", "每个学生分配了一个座位。"),
    ("allowance", "/əˈlaʊəns/", "n.", "津贴；零用钱；限额", "His parents give him a weekly allowance.", "他父母每周给他零用钱。"),
    ("alloy", "/ˈælɔɪ/", "n./v.", "合金；熔合", "Steel is an alloy of iron and carbon.", "钢是铁和碳的合金。"),
    ("alter", "/ˈɔːltər/", "v.", "改变；修改；变更", "The schedule has been altered.", "时间表已经改了。"),
    ("alternate", "/ɔːlˈtɜːnət/", "v./adj.", "交替；轮流；间隔的", "The meeting will be held on alternate weeks.", "会议每隔一周举行一次。"),
    ("altitude", "/ˈæltɪtjuːd/", "n.", "海拔；高度；高处", "The plane is flying at an altitude of 30,000 feet.", "飞机在3万英尺的高度飞行。"),
    ("amateur", "/ˈæmətər/", "n./adj.", "业余爱好者；业余的", "He is an amateur photographer.", "他是个业余摄影师。"),
    ("ambassador", "/æmˈbæsədər/", "n.", "大使；使者；代表", "She served as ambassador to France.", "她曾担任驻法国大使。"),
    ("ambiguous", "/æmˈbɪɡjuəs/", "adj.", "模棱两可的；含糊的", "His answer was ambiguous.", "他的回答模棱两可。"),
    ("amend", "/əˈmend/", "v.", "修改；修订；改善", "The constitution was amended in 1999.", "宪法在1999年进行了修订。"),
    ("ample", "/ˈæmpl/", "adj.", "充足的；丰富的；宽敞的", "There is ample evidence to support the claim.", "有充足的证据支持这一主张。"),
    ("amplify", "/ˈæmplɪfaɪ/", "v.", "放大；增强；扩充", "The microphone amplifies sound.", "麦克风放大声音。"),
    ("analogy", "/əˈnælədʒi/", "n.", "类比；比拟；类推", "The teacher drew an analogy between the heart and a pump.", "老师把心脏比作泵。"),
    ("anchor", "/ˈæŋkər/", "n./v.", "锚；主持人；抛锚", "The news anchor reported live from the scene.", "新闻主播从现场进行直播报道。"),
    ("anecdote", "/ˈænɪkdəʊt/", "n.", "轶事；趣闻", "He told an amusing anecdote about his childhood.", "他讲了一个关于童年的有趣轶事。"),
    ("anguish", "/ˈæŋɡwɪʃ/", "n./v.", "痛苦；苦恼；使痛苦", "She was in anguish over her loss.", "她因失去而痛苦不堪。"),
    ("animate", "/ˈænɪmeɪt/", "v./adj.", "使生气勃勃；有生命的", "The cartoon brings animated characters to life.", "这部动画片让动画角色活灵活现。"),
    ("annex", "/əˈneks/", "v./n.", "吞并；附加；附属建筑", "The country annexed the neighboring territory.", "该国吞并了邻国领土。"),
    ("anniversary", "/ˌænɪˈvɜːsəri/", "n.", "周年纪念日；周年", "Today is their 10th wedding anniversary.", "今天是他们结婚十周年纪念日。"),
    ("announce", "/əˈnaʊns/", "v.", "宣布；通知；声称", "The company announced a new product.", "公司宣布了一款新产品。"),
    ("annoy", "/əˈnɔɪ/", "v.", "使生气；使烦恼；打扰", "The noise annoyed the neighbors.", "噪音惹恼了邻居。"),
    ("anonymous", "/əˈnɒnɪməs/", "adj.", "匿名的；无名的；不具名的", "The donor wishes to remain anonymous.", "捐赠者希望保持匿名。"),
    ("antarctic", "/ænˈtɑːktɪk/", "adj./n.", "南极的；南极地区", "Scientists study climate change in the Antarctic.", "科学家们在南极研究气候变化。"),
    ("anthology", "/ænˈθɒlədʒi/", "n.", "选集；文集；诗选", "The anthology includes poems from 50 poets.", "这本文集收录了50位诗人的作品。"),
    ("anthropology", "/ˌænθrəˈpɒlədʒi/", "n.", "人类学", "She studied anthropology at university.", "她在大学学习人类学。"),
    ("antibiotic", "/ˌæntibaɪˈɒtɪk/", "n./adj.", "抗生素；抗菌的", "The doctor prescribed antibiotics for the infection.", "医生开了抗生素治疗感染。"),
    ("antique", "/ænˈtiːk/", "adj./n.", "古老的；古董；古玩", "She collects antique furniture.", "她收藏古董家具。"),
    ("anxiety", "/æŋˈzaɪəti/", "n.", "焦虑；忧虑；担心", "She felt anxiety before the exam.", "考试前她感到焦虑。"),
    ("apparatus", "/ˌæpəˈreɪtəs/", "n.", "器械；设备；仪器", "The laboratory has advanced apparatus.", "实验室有先进的设备。"),
    ("apparent", "/əˈpærənt/", "adj.", "明显的；表面上的", "The problem is apparent to everyone.", "问题对每个人来说都很明显。"),
    ("appeal", "/əˈpiːl/", "v./n.", "呼吁；上诉；吸引", "The charity appealed for donations.", "慈善机构呼吁捐款。"),
    ("appetite", "/ˈæpɪtaɪt/", "n.", "胃口；食欲；欲望", "Exercise can stimulate your appetite.", "运动能刺激食欲。"),
    ("applaud", "/əˈplɔːd/", "v.", "鼓掌；称赞；赞许", "The audience applauded loudly.", "观众热烈鼓掌。"),
    ("appliance", "/əˈplaɪəns/", "n.", "电器；器具；设备", "The store sells kitchen appliances.", "这家店卖厨房电器。"),
    ("applicable", "/əˈplɪkəbl/", "adj.", "适用的；合适的", "These rules are applicable to all members.", "这些规则适用于所有成员。"),
    ("appraisal", "/əˈpreɪzl/", "n.", "评价；鉴定；评估", "The manager gave her a positive appraisal.", "经理给了她积极的评价。"),
    ("appreciate", "/əˈpriːʃieɪt/", "v.", "欣赏；感激；增值", "I appreciate your kindness.", "我感激你的好意。"),
    ("apprehend", "/ˌæprɪˈhend/", "v.", "逮捕；理解；忧虑", "The police apprehended the suspect.", "警方逮捕了嫌疑人。"),
    ("apprentice", "/əˈprentɪs/", "n./v.", "学徒；徒弟", "He became an apprentice to a carpenter.", "他成了一个木匠的学徒。"),
    ("appropriate", "/əˈprəʊpriət/", "adj./v.", "适当的；拨用", "Wear appropriate clothing for the occasion.", "穿上适合该场合的衣服。"),
    ("approve", "/əˈpruːv/", "v.", "批准；赞成；认可", "The committee approved the plan.", "委员会批准了该计划。"),
    ("apt", "/æpt/", "adj.", "恰当的；聪明的；有...倾向的", "His remark was very apt.", "他的话非常恰当。"),
    ("aquatic", "/əˈkwætɪk/", "adj.", "水生的；水产的；水中的", "The pond is home to various aquatic plants.", "这个池塘有各种水生植物。"),
    ("arbitrary", "/ˈɑːbɪtrəri/", "adj.", "任意的；武断的；专制的", "The choice seemed completely arbitrary.", "这个选择似乎完全是任意的。"),
    ("arbitrate", "/ˈɑːbɪtreɪt/", "v.", "仲裁；公断；调解", "An independent expert arbitrated the dispute.", "一位独立专家仲裁了这起纠纷。"),
    ("arc", "/ɑːk/", "n.", "弧；弧形；弧光", "The rainbow formed a perfect arc.", "彩虹形成了一个完美的弧形。"),
    ("arch", "/ɑːtʃ/", "n./v./adj.", "拱门；拱形；使成拱形", "The cathedral has beautiful arches.", "大教堂有美丽的拱门。"),
    ("archaeology", "/ˌɑːkiˈɒlədʒi/", "n.", "考古学", "Archaeology reveals the secrets of ancient civilizations.", "考古学揭示了古代文明的秘密。"),
    ("architect", "/ˈɑːkɪtekt/", "n.", "建筑师；设计师；缔造者", "The architect designed an innovative building.", "这位建筑师设计了一座创新的建筑。"),
    ("archive", "/ˈɑːkaɪv/", "n./v.", "档案；存档；归档", "The archive contains historical documents.", "档案包含历史文件。"),
    ("ardent", "/ˈɑːdnt/", "adj.", "热情的；热烈的；炽热的", "She is an ardent supporter of the cause.", "她是这项事业的热心支持者。"),
    ("arena", "/əˈriːnə/", "n.", "竞技场；舞台；活动场所", "He entered the political arena at age 30.", "他30岁进入政坛。"),
    ("argument", "/ˈɑːɡjumənt/", "n.", "论点；争论；论证", "The argument was based on solid evidence.", "这个论点基于确凿的证据。"),
    ("arise", "/əˈraɪz/", "v.", "出现；产生；起因于", "A new opportunity has arisen.", "出现了一个新机会。"),
    ("aristocrat", "/ˈærɪstəkræt/", "n.", "贵族；贵族成员", "He was born into an aristocratic family.", "他出生在贵族家庭。"),
    ("arithmetic", "/əˈrɪθmətɪk/", "n.", "算术；计算", "Children learn basic arithmetic in primary school.", "孩子们在小学学习基础算术。"),
    ("armament", "/ˈɑːməmənt/", "n.", "军备；武器；武装", "The country increased its armament spending.", "该国增加了军备开支。"),
    ("arouse", "/əˈraʊz/", "v.", "引起；唤醒；激起", "His speech aroused great enthusiasm.", "他的演讲激起了极大的热情。"),
    ("arrange", "/əˈreɪndʒ/", "v.", "安排；整理；排列", "Can you arrange a meeting for Friday?", "你能安排周五的会议吗？"),
    ("array", "/əˈreɪ/", "n./v.", "排列；阵列；一系列", "There was a vast array of goods on display.", "展出了大量商品。"),
    ("arrogant", "/ˈærəɡənt/", "adj.", "傲慢的；自大的", "His arrogant attitude annoyed everyone.", "他傲慢的态度惹恼了所有人。"),
    ("articulate", "/ɑːˈtɪkjuleɪt/", "adj./v.", "善于表达的；清晰地表达", "She is an articulate speaker.", "她是个善于表达的演讲者。"),
    ("artillery", "/ɑːˈtɪləri/", "n.", "大炮；炮兵；火炮", "The army used heavy artillery in the battle.", "军队在战斗中使用了重型火炮。"),
    ("ascend", "/əˈsend/", "v.", "上升；攀登；登上", "The balloon ascended into the sky.", "气球升上了天空。"),
    ("ascertain", "/ˌæsəˈteɪn/", "v.", "查明；确定；弄清", "We need to ascertain the truth.", "我们需要查明真相。"),
    ("ascribe", "/əˈskraɪb/", "v.", "归因于；归功于", "The painting was ascribed to Picasso.", "这幅画被认为是毕加索的作品。"),
    ("aspect", "/ˈæspekt/", "n.", "方面；层面；面貌", "We should consider every aspect of the problem.", "我们应该考虑问题的每个方面。"),
    ("aspiration", "/ˌæspəˈreɪʃn/", "n.", "渴望；抱负；志向", "She has aspirations to become a doctor.", "她有成为医生的志向。"),
    ("assassinate", "/əˈsæsɪneɪt/", "v.", "暗杀；刺杀", "The president was assassinated in 1963.", "总统在1963年被暗杀。"),
    ("assault", "/əˈsɔːlt/", "n./v.", "袭击；攻击；突击", "The soldiers launched an assault on the fortress.", "士兵们对堡垒发起攻击。"),
    ("assemble", "/əˈsembl/", "v.", "集合；组装；聚集", "The students assembled in the hall.", "学生们在大厅集合。"),
    ("assert", "/əˈsɜːt/", "v.", "断言；主张；维护", "He asserted his innocence.", "他坚称自己无罪。"),
    ("assess", "/əˈses/", "v.", "评估；评定；估算", "We need to assess the damage.", "我们需要评估损失。"),
    ("asset", "/ˈæset/", "n.", "资产；财产；优点", "The company has total assets of $10 million.", "该公司总资产达1000万美元。"),
    ("assign", "/əˈsaɪn/", "v.", "分配；指派；布置", "The teacher assigned homework.", "老师布置了作业。"),
    ("assimilate", "/əˈsɪməleɪt/", "v.", "同化；吸收；融入", "Immigrants often assimilate into the host culture.", "移民往往会融入当地文化。"),
    ("assist", "/əˈsɪst/", "v./n.", "协助；帮助；援助", "Can you assist me with this task?", "你能帮我完成这个任务吗？"),
    ("associate", "/əˈsəʊsieɪt/", "v./n./adj.", "联系；关联；同事", "I associate summer with holidays.", "我把夏天和假期联系在一起。"),
    ("assume", "/əˈsjuːm/", "v.", "假设；承担；呈现", "I assume you have finished the report.", "我假设你已经完成了报告。"),
    ("assure", "/əˈʃʊər/", "v.", "保证；使确信；确保", "I assure you it is safe.", "我向你保证这是安全的。"),
    ("astronomy", "/əˈstrɒnəmi/", "n.", "天文学", "Astronomy is the study of celestial objects.", "天文学研究天体。"),
    ("asylum", "/əˈsaɪləm/", "n.", "庇护；避难；精神病院", "The refugee sought political asylum.", "难民寻求政治庇护。"),
    ("athlete", "/ˈæθliːt/", "n.", "运动员；体育家", "He is a professional athlete.", "他是一名职业运动员。"),
    ("atlas", "/ˈætləs/", "n.", "地图册；地图集", "The atlas shows the physical features of the world.", "地图册展示了世界的自然地理特征。"),
    ("atmosphere", "/ˈætməsfɪər/", "n.", "大气；气氛；环境", "The restaurant has a cozy atmosphere.", "这家餐厅有舒适的气氛。"),
    ("atom", "/ˈætəm/", "n.", "原子；微粒；极小量", "An atom consists of a nucleus and electrons.", "原子由原子核和电子组成。"),
    ("atrocity", "/əˈtrɒsəti/", "n.", "暴行；残忍；凶恶", "The war was marked by terrible atrocities.", "这场战争充满了可怕的暴行。"),
    ("attach", "/əˈtætʃ/", "v.", "附上；贴上；使附属", "Please attach the file to the email.", "请将文件附在邮件中。"),
    ("attain", "/əˈteɪn/", "v.", "达到；获得；实现", "She attained the highest score in the class.", "她在班上获得了最高分。"),
    ("attempt", "/əˈtempt/", "v./n.", "尝试；企图；努力", "She made an attempt to solve the puzzle.", "她尝试解开这个谜题。"),
    ("attend", "/əˈtend/", "v.", "参加；出席；照顾", "All staff must attend the meeting.", "所有员工必须参加会议。"),
    ("attitude", "/ˈætɪtjuːd/", "n.", "态度；看法；姿势", "A positive attitude helps in difficult times.", "积极的态度在困难时期有帮助。"),
    ("attorney", "/əˈtɜːni/", "n.", "律师；代理人", "She hired an attorney to handle the case.", "她聘请了一名律师处理此案。"),
    ("attract", "/əˈtrækt/", "v.", "吸引；引起；诱惑", "The exhibition attracted many visitors.", "展览吸引了许多参观者。"),
    ("attribute", "/əˈtrɪbjuːt/", "v./n.", "归因于；属性；特征", "She attributes her success to perseverance.", "她把成功归因于毅力。"),
    ("auction", "/ˈɔːkʃn/", "n./v.", "拍卖；竞拍", "The painting was sold at auction.", "这幅画在拍卖会上售出。"),
    ("audience", "/ˈɔːdiəns/", "n.", "观众；听众；读者", "The audience applauded the performance.", "观众为表演鼓掌。"),
    ("audit", "/ˈɔːdɪt/", "n./v.", "审计；查账；审核", "The company undergoes an annual audit.", "公司每年接受审计。"),
    ("authentic", "/ɔːˈθentɪk/", "adj.", "真正的；真实的；可信的", "This is an authentic antique.", "这是一件真正的古董。"),
    ("authority", "/ɔːˈθɒrəti/", "n.", "权威；当局；权力；专家", "The local authority is responsible for education.", "地方当局负责教育。"),
    ("authorize", "/ˈɔːθəraɪz/", "v.", "授权；批准；认可", "Only the manager can authorize payments.", "只有经理才能授权付款。"),
    ("automatic", "/ˌɔːtəˈmætɪk/", "adj.", "自动的；必然的", "The doors open automatically.", "门自动打开。"),
    ("autonomous", "/ɔːˈtɒnəməs/", "adj.", "自治的；自主的；独立的", "The region is an autonomous province.", "该地区是一个自治省。"),
    ("available", "/əˈveɪləbl/", "adj.", "可用的；可获得的；有效的", "Tickets are still available.", "门票还有售。"),
    ("average", "/ˈævərɪdʒ/", "n./adj./v.", "平均的；普通的；平均", "The average temperature is 20 degrees.", "平均气温是20度。"),
    ("aviation", "/ˌeɪviˈeɪʃn/", "n.", "航空；飞行术", "He has a career in aviation.", "他从事航空业。"),
    ("avoid", "/əˈvɔɪd/", "v.", "避免；回避；预防", "You should avoid making the same mistake.", "你应该避免犯同样的错误。"),
    ("await", "/əˈweɪt/", "v.", "等候；等待；期待", "She is awaiting the exam results.", "她在等待考试结果。"),
    ("award", "/əˈwɔːd/", "n./v.", "奖励；奖品；授予", "She won the Best Actress award.", "她获得了最佳女演员奖。"),
    ("aware", "/əˈweər/", "adj.", "意识到；知道的；察觉的", "Are you aware of the rules?", "你知道规则吗？"),
    ("awe", "/ɔː/", "n./v.", "敬畏；惊叹；使敬畏", "The Grand Canyon fills visitors with awe.", "大峡谷让游客充满敬畏。"),
    ("awkward", "/ˈɔːkwəd/", "adj.", "笨拙的；尴尬的；棘手的", "There was an awkward silence.", "出现了尴尬的沉默。"),
    ("axis", "/ˈæksɪs/", "n.", "轴；轴线；中心线", "The Earth rotates on its axis.", "地球绕着地轴旋转。"),
    ("bachelor", "/ˈbætʃələr/", "n.", "学士；单身汉", "She earned a Bachelor of Arts degree.", "她获得了文学学士学位。"),
    ("bacterium", "/bækˈtɪəriəm/", "n.", "细菌", "The bacterium causes food poisoning.", "这种细菌导致食物中毒。"),
    ("baffle", "/ˈbæfl/", "v.", "使困惑；难住", "The puzzle baffled everyone.", "这个谜题难住了所有人。"),
    ("baggage", "/ˈbæɡɪdʒ/", "n.", "行李；辎重", "Please collect your baggage from carousel 3.", "请从3号传送带领取行李。"),
    ("balance", "/ˈbæləns/", "n./v.", "平衡；余额；权衡", "Try to keep a balance between work and life.", "尽量保持工作和生活的平衡。"),
    ("bald", "/bɔːld/", "adj.", "秃头的；光秃的；明显的", "He started going bald in his thirties.", "他三十多岁开始秃头。"),
    ("ballet", "/ˈbæleɪ/", "n.", "芭蕾舞；芭蕾舞剧", "She has been learning ballet since age five.", "她从五岁开始学芭蕾。"),
    ("ballot", "/ˈbælət/", "n./v.", "选票；投票；投票权", "The election was decided by a secret ballot.", "选举通过无记名投票决定。"),
    ("ban", "/bæn/", "v./n.", "禁止；禁令；取缔", "The government banned smoking in public places.", "政府禁止在公共场所吸烟。"),
    ("band", "/bænd/", "n./v.", "乐队；带子；联合", "The band performed a new song.", "乐队表演了一首新歌。"),
    ("bankrupt", "/ˈbæŋkrʌpt/", "adj./v./n.", "破产的；使破产；破产者", "The company went bankrupt last year.", "这家公司去年破产了。"),
    ("banner", "/ˈbænər/", "n.", "横幅；旗帜；标语", "The banner read Welcome to the Conference.", "横幅上写着欢迎参加大会。"),
    ("banquet", "/ˈbæŋkwɪt/", "n.", "宴会；盛宴；筵席", "A grand banquet was held in honor of the guests.", "为贵宾举行了盛大的宴会。"),
    ("barely", "/ˈbeəli/", "adv.", "几乎不；勉强地；仅仅", "She could barely hear him.", "她几乎听不到他说话。"),
    ("bargain", "/ˈbɑːɡɪn/", "n./v.", "讨价还价；便宜货；协议", "I got a good bargain on this jacket.", "这件夹克我买得很便宜。"),
    ("bark", "/bɑːk/", "n./v.", "树皮；狗叫；咆哮", "The dog barked at strangers.", "狗对着陌生人叫。"),
    ("barn", "/bɑːn/", "n.", "谷仓；畜棚；车库", "The farmer stored hay in the barn.", "农夫把干草储存在谷仓里。"),
    ("barrel", "/ˈbærəl/", "n.", "桶；枪管；一桶的量", "The price of oil is $80 per barrel.", "石油价格是每桶80美元。"),
    ("barren", "/ˈbærən/", "adj.", "贫瘠的；不生育的；无结果的", "The desert is a barren landscape.", "沙漠是一片贫瘠的土地。"),
    ("basement", "/ˈbeɪsmənt/", "n.", "地下室；地窖", "The basement flooded after the heavy rain.", "大雨后地下室被淹了。"),
    ("basin", "/ˈbeɪsn/", "n.", "盆地；水盆；流域", "The Amazon basin covers a vast area.", "亚马逊河流域面积广阔。"),
    ("basis", "/ˈbeɪsɪs/", "n.", "基础；根据；基准", "The decision was made on the basis of the evidence.", "决定是根据证据做出的。"),
    ("batch", "/bætʃ/", "n.", "一批；一组；一批生产量", "The first batch of products has shipped.", "第一批产品已发货。"),
    ("battery", "/ˈbætəri/", "n.", "电池；蓄电池；一系列", "The car battery needs to be replaced.", "汽车电池需要更换。"),
    ("bay", "/beɪ/", "n.", "海湾；港湾；隔间", "The ship anchored in the bay.", "船在海湾抛锚了。"),
    ("beam", "/biːm/", "n./v.", "梁；光线；笑容满面", "Sunlight streamed through the beam.", "阳光穿过光束。"),
    ("bean", "/biːn/", "n.", "豆；豆类；豆子", "Coffee beans are grown in tropical regions.", "咖啡豆种植在热带地区。"),
    ("bear", "/beər/", "v./n.", "忍受；承担；生；熊", "I cant bear the pain anymore.", "我再也无法忍受这种疼痛。"),
    ("bearing", "/ˈbeərɪŋ/", "n.", "关系；方位；轴承；举止", "His opinion has no bearing on the decision.", "他的意见与决定无关。"),
    ("beast", "/biːst/", "n.", "兽；野兽；人面兽心的人", "The lion is called the king of beasts.", "狮子被称为百兽之王。"),
    ("behalf", "/bɪˈhɑːf/", "n.", "代表；利益；方面", "He acted on behalf of his client.", "他代表他的客户行事。"),
    ("behave", "/bɪˈheɪv/", "v.", "表现；行为；举止", "Children should behave well in school.", "孩子在学校应该表现良好。"),
    ("behavior", "/bɪˈheɪvjər/", "n.", "行为；举止；习性", "His behavior was unacceptable.", "他的行为不可接受。"),
    ("being", "/ˈbiːɪŋ/", "n.", "存在；生物；本质", "Human beings are social creatures.", "人类是社会性动物。"),
    ("belief", "/bɪˈliːf/", "n.", "信念；信仰；相信", "She has strong religious beliefs.", "她有强烈的宗教信仰。"),
    ("belly", "/ˈbeli/", "n.", "肚子；腹部；胃", "The baby slept on its belly.", "婴儿趴着睡觉。"),
    ("belongings", "/bɪˈlɒŋɪŋz/", "n.", "财产；所有物；行李", "Please take all your personal belongings.", "请带走你所有个人物品。"),
    ("benchmark", "/ˈbentʃmɑːk/", "n./v.", "基准；标杆；衡量标准", "This report sets a benchmark for the industry.", "这份报告为行业设立了基准。"),
    ("beneficial", "/ˌbenɪˈfɪʃl/", "adj.", "有益的；有利的；有帮助的", "Regular exercise is beneficial to health.", "经常锻炼有益健康。"),
    ("benefit", "/ˈbenɪfɪt/", "n./v.", "利益；好处；受益于", "The new tax policy benefits small businesses.", "新税收政策有利于小企业。"),
    ("benevolent", "/bəˈnevələnt/", "adj.", "仁慈的；慈善的；乐善好施的", "The benevolent donor gave millions to charity.", "这位仁慈的捐赠者向慈善机构捐了数百万。"),
    ("besides", "/bɪˈsaɪdz/", "prep./adv.", "除了...之外；而且", "Besides English, she speaks French and German.", "除了英语，她还说法语和德语。"),
]
