# Low-frequency words (advanced/less common CET-6 and 考研 vocabulary)
LOW_WORDS_A = [
    ("abdomen", "/ˈæbdəmən/", "n.", "腹部；下腹", "The pain was in his lower abdomen.", "疼痛位于他的下腹部。"),
    ("abnormal", "/æbˈnɔːml/", "adj.", "反常的；异常的；不规则的", "Abnormal weather patterns have become more common.", "异常天气模式变得更加常见。"),
    ("abolish", "/əˈbɒlɪʃ/", "v.", "废除；废止；取消", "Slavery was abolished in the 19th century.", "奴隶制在19世纪被废除。"),
    ("aboriginal", "/ˌæbəˈrɪdʒənl/", "adj./n.", "土著的；原始的；土著居民", "The aboriginal people have lived here for thousands of years.", "土著居民在这里生活了数千年。"),
    ("abound", "/əˈbaʊnd/", "v.", "丰富；盛产；充满", "Wildlife abounds in this region.", "这个地区野生动物丰富。"),
    ("abreast", "/əˈbrest/", "adv.", "并肩地；并排；了解最新情况", "Keep abreast of the latest developments.", "了解最新发展情况。"),
    ("abrupt", "/əˈbrʌpt/", "adj.", "突然的；唐突的；陡峭的", "The road came to an abrupt end.", "道路突然到了尽头。"),
    ("absent", "/ˈæbsənt/", "adj.", "缺席的；不在的；心不在焉的", "He was absent from school due to illness.", "他因病缺课。"),
    ("absolute", "/ˈæbsəluːt/", "adj.", "绝对的；完全的；专制的", "She has absolute authority in this matter.", "她在这件事上有绝对权威。"),
    ("absorb", "/əbˈzɔːb/", "v.", "吸收；吸引；使专心", "The sponge absorbs water quickly.", "海绵吸水很快。"),
    ("absorption", "/əbˈzɔːpʃn/", "n.", "吸收；专注；合并", "His absorption in his work made him oblivious.", "他对工作的专注让他浑然不觉。"),
    ("abstain", "/əbˈsteɪn/", "v.", "戒绝；弃权；避免", "He abstained from alcohol for health reasons.", "他因健康原因戒酒了。"),
    ("abstract", "/ˈæbstrækt/", "adj./n./v.", "抽象的；摘要；提取", "The concept is too abstract for children.", "这个概念对孩子们来说太抽象了。"),
    ("absurd", "/əbˈsɜːd/", "adj.", "荒谬的；可笑的；不合理的", "The idea is completely absurd.", "这个想法完全荒谬。"),
    ("abundance", "/əˈbʌndəns/", "n.", "丰富；充裕；大量", "There is an abundance of job opportunities.", "有大量的工作机会。"),
    ("abuse", "/əˈbjuːs/", "n./v.", "滥用；虐待；辱骂", "Child abuse is a serious crime.", "虐待儿童是严重犯罪。"),
    ("academic", "/ˌækəˈdemɪk/", "adj./n.", "学术的；学院的；学者", "She has a strong academic background.", "她有很强的学术背景。"),
    ("academy", "/əˈkædəmi/", "n.", "学院；研究院；学会", "He attended the military academy.", "他上了军事学院。"),
    ("accelerate", "/əkˈseləreɪt/", "v.", "加速；促进；催促", "The car accelerated rapidly.", "汽车迅速加速。"),
    ("accent", "/ˈæksent/", "n./v.", "口音；重音；强调", "She speaks with a strong French accent.", "她说话有浓重的法国口音。"),
    ("acceptable", "/əkˈseptəbl/", "adj.", "可接受的；合意的；可以忍受的", "The proposal is acceptable to both sides.", "这个提议双方都能接受。"),
    ("acceptance", "/əkˈseptəns/", "n.", "接受；认可；容纳", "The idea gained widespread acceptance.", "这个想法得到了广泛接受。"),
    ("access", "/ˈækses/", "n./v.", "进入；通道；访问权限", "The building has wheelchair access.", "该建筑有轮椅通道。"),
    ("accessory", "/əkˈsesəri/", "n./adj.", "附件；从犯；辅助的", "She bought accessories to match her dress.", "她买了搭配裙子的配饰。"),
    ("accidental", "/ˌæksɪˈdentl/", "adj.", "意外的；偶然的；非主要的", "The discovery was accidental.", "这个发现是偶然的。"),
    ("acclaim", "/əˈkleɪm/", "v./n.", "赞扬；欢呼；称赞", "The movie received critical acclaim.", "这部电影获得了好评。"),
    ("accommodate", "/əˈkɒmədeɪt/", "v.", "容纳；向...提供住处；适应", "The hotel can accommodate 300 guests.", "这家酒店可以容纳300位客人。"),
    ("accompany", "/əˈkʌmpəni/", "v.", "陪伴；伴随；伴奏", "She accompanied him to the hospital.", "她陪他去了医院。"),
    ("accomplish", "/əˈkʌmplɪʃ/", "v.", "完成；实现；达到", "He accomplished his mission.", "他完成了任务。"),
    ("accord", "/əˈkɔːd/", "n./v.", "一致；协议；给予", "The two sides reached an accord.", "双方达成了一致。"),
    ("accordance", "/əˈkɔːdns/", "n.", "一致；按照；根据", "We acted in accordance with the rules.", "我们按照规则行事。"),
    ("accordingly", "/əˈkɔːdɪŋli/", "adv.", "相应地；因此；于是", "The situation has changed, and we must act accordingly.", "情况变了，我们必须相应地行动。"),
    ("account", "/əˈkaʊnt/", "n./v.", "账户；说明；解释", "He gave a detailed account of the incident.", "他对事件做了详细说明。"),
    ("accumulate", "/əˈkjuːmjəleɪt/", "v.", "积累；积聚；堆积", "Dust accumulates quickly on the shelves.", "架子上很快就会积灰。"),
    ("accuracy", "/ˈækjərəsi/", "n.", "准确；精确；准确度", "The accuracy of the data is crucial.", "数据的准确性至关重要。"),
    ("accuse", "/əˈkjuːz/", "v.", "指控；指责；控告", "She accused him of lying.", "她指责他说谎。"),
    ("accustomed", "/əˈkʌstəmd/", "adj.", "习惯的；适应的；通常的", "She is accustomed to getting up early.", "她习惯早起。"),
    ("ache", "/eɪk/", "v./n.", "疼痛；渴望；酸痛", "My head aches after reading for hours.", "读了几个小时后我头疼。"),
    ("achieve", "/əˈtʃiːv/", "v.", "实现；达到；取得", "She achieved her goal of losing weight.", "她实现了减肥的目标。"),
    ("acknowledge", "/əkˈnɒlɪdʒ/", "v.", "承认；致谢；确认", "He acknowledged his mistake.", "他承认了自己的错误。"),
    ("acquaintance", "/əˈkweɪntəns/", "n.", "熟人；相识；了解", "I made his acquaintance at a conference.", "我在一次会议上认识了他。"),
    ("acquire", "/əˈkwaɪər/", "v.", "获得；学到；收购", "She acquired a good knowledge of French.", "她学到了很好的法语知识。"),
    ("acquisition", "/ˌækwɪˈzɪʃn/", "n.", "获得；收购；习得", "The company made a new acquisition.", "公司进行了一次新的收购。"),
    ("activate", "/ˈæktɪveɪt/", "v.", "激活；启动；使活动", "Press the button to activate the device.", "按下按钮启动设备。"),
    ("acute", "/əˈkjuːt/", "adj.", "急性的；敏锐的；剧烈的", "She has acute hearing.", "她听觉敏锐。"),
    ("adapt", "/əˈdæpt/", "v.", "适应；改编；改装", "The film was adapted from a novel.", "这部电影改编自一部小说。"),
    ("addict", "/ˈædɪkt/", "n./v.", "上瘾者；使上瘾；沉迷", "He is a video game addict.", "他是个电子游戏迷。"),
    ("addition", "/əˈdɪʃn/", "n.", "增加；附加；加法", "In addition to English, she speaks Japanese.", "除了英语，她还会说日语。"),
    ("adequate", "/ˈædɪkwət/", "adj.", "足够的；适当的；合格的", "The supply is adequate for our needs.", "供应量足以满足我们的需求。"),
    ("adhere", "/ədˈhɪər/", "v.", "粘附；遵守；坚持", "We must adhere to the company policy.", "我们必须遵守公司政策。"),
    ("adjacent", "/əˈdʒeɪsnt/", "adj.", "邻近的；毗连的；紧挨着的", "The building is adjacent to the park.", "该建筑毗邻公园。"),
    ("adjust", "/əˈdʒʌst/", "v.", "调整；适应；调节", "You need to adjust your attitude.", "你需要调整你的态度。"),
    ("administer", "/ədˈmɪnɪstər/", "v.", "管理；执行；给予", "The nurse administered the medicine.", "护士给服了药。"),
    ("admire", "/ədˈmaɪər/", "v.", "钦佩；赞赏；欣赏", "I admire her dedication to her work.", "我钦佩她对工作的投入。"),
    ("admission", "/ədˈmɪʃn/", "n.", "承认；准入；入场费", "Admission to the museum is free.", "博物馆免费入场。"),
    ("adolescent", "/ˌædəˈlesnt/", "n./adj.", "青少年；青春期的", "Adolescent behavior can be difficult to handle.", "青少年的行为可能难以处理。"),
    ("adopt", "/əˈdɒpt/", "v.", "采用；收养；正式通过", "They decided to adopt a child.", "他们决定收养一个孩子。"),
    ("adore", "/əˈdɔːr/", "v.", "崇拜；爱慕；喜爱", "She adores her grandchildren.", "她非常喜欢她的孙子孙女。"),
    ("advance", "/ədˈvɑːns/", "v./n./adj.", "前进；进步；预先的", "Technology has advanced rapidly.", "技术进步迅速。"),
    ("advantage", "/ədˈvɑːntɪdʒ/", "n.", "优势；有利条件；利益", "Being tall is an advantage in basketball.", "个子高是打篮球的优势。"),
    ("adventure", "/ədˈventʃər/", "n./v.", "冒险；奇遇；冒险经历", "They went on an exciting adventure.", "他们进行了一次激动人心的冒险。"),
    ("adverse", "/ədˈvɜːs/", "adj.", "不利的；相反的；逆向的", "The drug can cause adverse effects.", "这种药物会引起不良反应。"),
    ("advertise", "/ˈædvətaɪz/", "v.", "做广告；宣传；公告", "The company advertised for a new manager.", "公司登广告招聘新经理。"),
    ("advocate", "/ˈædvəkeɪt/", "v./n.", "提倡；拥护；辩护人", "She advocates for environmental protection.", "她提倡环境保护。"),
    ("aerial", "/ˈeəriəl/", "adj./n.", "空中的；航空的；天线", "The aerial view of the coastline is stunning.", "海岸线的空中景色令人惊叹。"),
    ("aerospace", "/ˈeərəspeɪs/", "n.", "航空航天；航天工业", "He works in the aerospace industry.", "他在航空航天业工作。"),
    ("aesthetic", "/iːsˈθetɪk/", "adj.", "美学的；审美的；艺术的", "The garden has great aesthetic appeal.", "这个花园具有很高的审美吸引力。"),
    ("affair", "/əˈfeər/", "n.", "事务；私事；事件", "The company manages its financial affairs well.", "公司财务管理得很好。"),
    ("affiliate", "/əˈfɪlieɪt/", "v./n.", "使附属；加入；分支机构", "The local club is affiliated with the national organization.", "当地俱乐部隶属于全国性组织。"),
    ("affirm", "/əˈfɜːm/", "v.", "肯定；断言；证实", "The court affirmed the decision.", "法院维持了原判。"),
    ("afflict", "/əˈflɪkt/", "v.", "使痛苦；折磨；使苦恼", "She was afflicted with a rare disease.", "她患有一种罕见的疾病。"),
    ("affluent", "/ˈæfluənt/", "adj.", "富裕的；富足的；丰富的", "He grew up in an affluent family.", "他在富裕的家庭长大。"),
    ("agency", "/ˈeɪdʒənsi/", "n.", "代理；机构；中介", "She works for a travel agency.", "她在一家旅行社工作。"),
    ("agenda", "/əˈdʒendə/", "n.", "议程；议事日程；日常工作事项", "What is on the agenda for todays meeting?", "今天会议的议程是什么？"),
    ("aggravate", "/ˈæɡrəveɪt/", "v.", "加重；使恶化；激怒", "The stress aggravated his condition.", "压力加重了他的病情。"),
    ("aggregate", "/ˈæɡrɪɡət/", "v./n./adj.", "总计；集合；合计的", "The aggregate of all sales exceeded expectations.", "总销售额超过了预期。"),
    ("aggression", "/əˈɡreʃn/", "n.", "侵略；攻击；侵犯", "The aggression was condemned worldwide.", "侵略行为受到全世界谴责。"),
    ("agony", "/ˈæɡəni/", "n.", "极度痛苦；挣扎；苦恼", "She was in agony after the operation.", "手术后她处于极度痛苦中。"),
    ("agreeable", "/əˈɡriːəbl/", "adj.", "令人愉快的；同意的；适合的", "We spent an agreeable evening together.", "我们一起度过了一个愉快的晚上。"),
    ("alien", "/ˈeɪliən/", "adj./n.", "外国的；陌生的；外星人", "The culture was alien to me.", "这种文化对我来说很陌生。"),
    ("alienate", "/ˈeɪliəneɪt/", "v.", "使疏远；使不友好；离间", "His rude behavior alienated his friends.", "他的粗鲁行为让朋友们疏远了他。"),
    ("allege", "/əˈledʒ/", "v.", "断言；声称；指控", "The report alleges widespread corruption.", "报告声称存在普遍的腐败。"),
    ("allegiance", "/əˈliːdʒəns/", "n.", "忠诚；效忠；拥护", "She pledged allegiance to her country.", "她宣誓效忠祖国。"),
    ("alleviate", "/əˈliːvieɪt/", "v.", "减轻；缓解；缓和", "The medicine alleviated her symptoms.", "药物缓解了她的症状。"),
    ("alliance", "/əˈlaɪəns/", "n.", "联盟；同盟；联合", "The two parties formed an alliance.", "两党结成了联盟。"),
    ("allocate", "/ˈæləkeɪt/", "v.", "分配；拨出；划拨", "Resources were allocated to the project.", "资源被分配给了该项目。"),
    ("allowance", "/əˈlaʊəns/", "n.", "津贴；零用钱；补贴", "He receives a monthly allowance from his parents.", "他每月从父母那里得到零用钱。"),
    ("alloy", "/ˈælɔɪ/", "n./v.", "合金；熔合；混合", "Brass is an alloy of copper and zinc.", "黄铜是铜和锌的合金。"),
    ("alter", "/ˈɔːltər/", "v.", "改变；修改；变更", "The design has been altered several times.", "设计已经修改了好几次。"),
    ("alternate", "/ɔːlˈtɜːnət/", "v./adj.", "交替；轮流；间隔的", "The class meets on alternate days.", "这门课隔天上课。"),
    ("alternative", "/ɔːlˈtɜːnətɪv/", "n./adj.", "替代方案；替代的；另外的", "We need to find an alternative route.", "我们需要找一条替代路线。"),
    ("altitude", "/ˈæltɪtjuːd/", "n.", "高度；海拔；高处", "The mountain has an altitude of 5000 meters.", "这座山海拔5000米。"),
    ("amateur", "/ˈæmətər/", "n./adj.", "业余爱好者；业余的；不熟练的", "The competition is open to amateurs only.", "比赛只对业余爱好者开放。"),
    ("amaze", "/əˈmeɪz/", "v.", "使惊奇；使惊愕；使惊叹", "Her performance amazed the audience.", "她的表演令观众惊叹。"),
    ("ambassador", "/æmˈbæsədər/", "n.", "大使；使者；代表", "He was appointed ambassador to Japan.", "他被任命为驻日大使。"),
    ("ambiguous", "/æmˈbɪɡjuəs/", "adj.", "模棱两可的；含糊的；不明确的", "The contract language is ambiguous.", "合同的措辞模棱两可。"),
    ("ambition", "/æmˈbɪʃn/", "n.", "雄心；野心；追求", "She has the ambition to become CEO.", "她有成为CEO的雄心。"),
    ("amend", "/əˈmend/", "v.", "修改；修订；纠正", "The constitution was amended in 1995.", "宪法于1995年修订。"),
    ("amid", "/əˈmɪd/", "prep.", "在...中；在...当中", "The house stood amid the trees.", "房子坐落在树林中。"),
    ("ammunition", "/ˌæmjuˈnɪʃn/", "n.", "弹药；军火；武器", "The troops ran out of ammunition.", "部队的弹药耗尽了。"),
    ("ample", "/ˈæmpl/", "adj.", "充足的；宽敞的；丰富的", "There is ample space in the garden.", "花园里有足够的空间。"),
    ("amplify", "/ˈæmplɪfaɪ/", "v.", "放大；增强；扩大", "The sound system amplifies the music.", "音响系统放大音乐。"),
    ("analogy", "/əˈnælədʒi/", "n.", "类比；比拟；类推", "The teacher drew an analogy between the heart and a pump.", "老师将心脏比作泵。"),
    ("analysis", "/əˈnæləsɪs/", "n.", "分析；解析；分解", "The data analysis revealed interesting patterns.", "数据分析揭示了有趣的模式。"),
    ("analytic", "/ˌænəˈlɪtɪk/", "adj.", "分析的；解析的；善于分析的", "She has strong analytic skills.", "她有很强的分析能力。"),
    ("ancestor", "/ˈænsestər/", "n.", "祖先；祖宗；先驱", "His ancestors came from Ireland.", "他的祖先来自爱尔兰。"),
    ("ancient", "/ˈeɪnʃənt/", "adj.", "古代的；古老的；年老的", "Ancient civilizations built amazing structures.", "古代文明建造了惊人的建筑。"),
    ("anecdote", "/ˈænɪkdəʊt/", "n.", "轶事；趣闻；短故事", "He told an amusing anecdote about his travels.", "他讲了一个关于旅行的有趣轶事。"),
    ("angle", "/ˈæŋɡl/", "n./v.", "角度；观点；钓鱼", "Look at the problem from a different angle.", "从不同角度看这个问题。"),
    ("anguish", "/ˈæŋɡwɪʃ/", "n./v.", "痛苦；苦恼；使痛苦", "She cried out in anguish.", "她痛苦地大叫。"),
    ("animate", "/ˈænɪmeɪt/", "v./adj.", "使生动；动画制作；有生命的", "The discussion became more animated.", "讨论变得更加热烈。"),
    ("ankle", "/ˈæŋkl/", "n.", "脚踝；踝关节", "She twisted her ankle while running.", "她跑步时扭伤了脚踝。"),
    ("anniversary", "/ˌænɪˈvɜːsəri/", "n.", "周年纪念日；周年纪念", "Today is their wedding anniversary.", "今天是他们的结婚纪念日。"),
    ("announce", "/əˈnaʊns/", "v.", "宣布；通知；声称", "The president announced his resignation.", "总统宣布辞职。"),
    ("annoy", "/əˈnɔɪ/", "v.", "使恼怒；使烦恼；打扰", "The constant noise annoyed him.", "持续的噪音使他烦恼。"),
    ("annual", "/ˈænjuəl/", "adj./n.", "每年的；年度的；年报", "The company publishes an annual report.", "公司发布年度报告。"),
    ("anonymous", "/əˈnɒnɪməs/", "adj.", "匿名的；无名的；不具名的", "The donor wishes to remain anonymous.", "捐款人希望保持匿名。"),
    ("anticipate", "/ænˈtɪsɪpeɪt/", "v.", "预期；期望；预料", "We anticipate strong demand for the new product.", "我们预计新产品会有强劲需求。"),
    ("antique", "/ænˈtiːk/", "adj./n.", "古老的；古董的；古董", "She collects antique furniture.", "她收藏古董家具。"),
    ("anxiety", "/æŋˈzaɪəti/", "n.", "焦虑；忧虑；担心", "She felt great anxiety before the interview.", "面试前她感到非常焦虑。"),
    ("apart", "/əˈpɑːt/", "adv./adj.", "分开地；分离地；有距离的", "The two houses are 100 meters apart.", "这两栋房子相距100米。"),
    ("apartment", "/əˈpɑːtmənt/", "n.", "公寓；单元房；房间", "They rent an apartment in the city center.", "他们在市中心租了一套公寓。"),
    ("apologize", "/əˈpɒlədʒaɪz/", "v.", "道歉；认错；谢罪", "I apologize for the delay.", "我为延误道歉。"),
    ("apparatus", "/ˌæpəˈreɪtəs/", "n.", "器械；设备；装置", "The laboratory is equipped with expensive apparatus.", "实验室配备了昂贵的设备。"),
    ("apparent", "/əˈpærənt/", "adj.", "明显的；显而易见的；表面上的", "His disappointment was apparent.", "他的失望是显而易见的。"),
    ("appeal", "/əˈpiːl/", "v./n.", "呼吁；上诉；吸引；请求", "The idea appeals to young people.", "这个想法吸引年轻人。"),
    ("appetite", "/ˈæpɪtaɪt/", "n.", "胃口；食欲；欲望", "The fresh air gave him an appetite.", "新鲜空气让他有了食欲。"),
    ("applaud", "/əˈplɔːd/", "v.", "鼓掌；称赞；赞许", "The audience applauded enthusiastically.", "观众热情地鼓掌。"),
    ("appliance", "/əˈplaɪəns/", "n.", "电器；器具；设备", "The store sells household appliances.", "这家店卖家用电器。"),
    ("applicable", "/əˈplɪkəbl/", "adj.", "适用的；合适的；有效的", "These rules are applicable to everyone.", "这些规则适用于每个人。"),
    ("applicant", "/ˈæplɪkənt/", "n.", "申请人；候选者", "There were 100 applicants for the job.", "有100人申请这份工作。"),
    ("appoint", "/əˈpɔɪnt/", "v.", "任命；委派；指定", "A committee was appointed to investigate.", "任命了一个委员会进行调查。"),
    ("appraisal", "/əˈpreɪzl/", "n.", "评价；评估；鉴定", "The employee received a positive appraisal.", "这名员工收到了积极的评价。"),
    ("appreciate", "/əˈpriːʃieɪt/", "v.", "欣赏；感激；增值", "I appreciate your timely help.", "我感谢你及时的帮助。"),
    ("approach", "/əˈprəʊtʃ/", "v./n.", "接近；靠近；方法；途径", "Winter is approaching.", "冬天就要来了。"),
    ("appropriate", "/əˈprəʊpriət/", "adj./v.", "适当的；合适的；拨出", "Choose the appropriate word for the context.", "选择适合上下文的词。"),
    ("approve", "/əˈpruːv/", "v.", "批准；赞成；认可", "The board approved the budget.", "董事会批准了预算。"),
    ("approximate", "/əˈprɒksɪmət/", "adj./v.", "大约的；近似的；接近", "The approximate cost is $200.", "大约费用是200美元。"),
    ("arbitrary", "/ˈɑːbɪtrəri/", "adj.", "任意的；武断的；专制的", "The decision seemed arbitrary.", "这个决定似乎是武断的。"),
    ("arch", "/ɑːtʃ/", "n./v./adj.", "拱门；拱形；使成拱形", "The bridge has a beautiful arch.", "这座桥有一个美丽的拱形。"),
    ("archaeology", "/ˌɑːkiˈɒlədʒi/", "n.", "考古学", "Archaeology reveals the secrets of ancient societies.", "考古学揭示了古代社会的秘密。"),
    ("architect", "/ˈɑːkɪtekt/", "n.", "建筑师；设计师；缔造者", "The architect designed an award-winning building.", "这位建筑师设计了一座获奖建筑。"),
    ("archive", "/ˈɑːkaɪv/", "n./v.", "档案；档案馆；存档", "The archive contains rare historical documents.", "档案馆收藏了珍贵的历史文件。"),
    ("arena", "/əˈriːnə/", "n.", "竞技场；舞台；活动场所", "She entered the political arena.", "她进入了政治舞台。"),
]
